- pkg/controller/ingress/types.go
Renamed ingress annotations to "ingress.appscode.com"
@sajibcse68 This needs a change on UI.
> Renamed ingress annotations to "ingress.appscode.com"

- cmd/voyager/app/daemon.go
- cmd/voyager/app/options/options.go
- cmd/voyager/app/watcher.go
- pkg/controller/ingress/handler.go
- pkg/controller/ingress/types.go
Ingress class handled by voyager. Unset by default. Set to voyager to only handle ingress with annotation kubernetes.io/ingress-class=voyager.
> add ingress-class

- pkg/controller/ingress/create.go
- pkg/controller/ingress/handler_test.go
- pkg/controller/ingress/parser.go
- pkg/controller/ingress/parser_test.go
- pkg/controller/ingress/resource.go
- pkg/controller/ingress/types.go
- Use Secret name for HAProxy stats
- Use NodeSelector instead of deamon name
Resolves #18
> Resolve #18

- hack/docker/haproxy/1.7.2/runit.sh
- hack/docker/haproxy/1.7.2/sv/reloader/run
ref: http://stackoverflow.com/a/27787551/5941449
> Pass KLOADER_ARGS as env variable

- pkg/controller/ingress/template/template.go
> Remove ALPN h2 for https

- hack/deploy/test-ingress.yaml
- pkg/controller/ingress/create.go
- pkg/controller/ingress/handler.go
- pkg/controller/ingress/handler_test.go
- test/e2e/ingress.go
> Enable GKE

- cmd/voyager/main.go
> cloud-provider & cloud-name is not required for unknown providers.

- docs/user-guide/README.md
- docs/user-guide/component/ingress/README.md
- glide.lock
- pkg/controller/ingress/create.go
- pkg/controller/ingress/delete.go
- pkg/controller/ingress/resource.go
- pkg/controller/ingress/resource_test.go
- pkg/controller/ingress/types.go
- test/e2e/ingress.go
> Rename Daemon type to HostPort

- hack/docker/haproxy/1.7.5/Dockerfile
- hack/docker/haproxy/1.7.5/runit.sh
- hack/docker/haproxy/1.7.5/setup.sh
- hack/docker/haproxy/1.7.5/sv/haproxy/run
- hack/docker/haproxy/1.7.5/sv/reloader/reload
- hack/docker/haproxy/1.7.5/sv/reloader/run
> Use HAProxy 1.7.5

- cmd/voyager/app/options/options.go
- test/testframework/test_context.go
I have already pushed this image: https://hub.docker.com/r/appscode/haproxy/tags/
> Change HAProxy image to 1.7.5-1.5.5

- pkg/controller/ingress/delete.go
> Ensure pod delete

- pkg/controller/ingress/create.go
- pkg/controller/ingress/handler.go
- pkg/controller/ingress/parser.go
- pkg/controller/ingress/types.go
- pkg/controller/ingress/update.go
- test/e2e/ingress.go
Fixes #100 #103 
cc @julianvmodesto
> Add user provided annotations in LoadBalancer in Service/Pods

- chart/voyager/README.md
- chart/voyager/templates/NOTES.txt
- chart/voyager/templates/deployment.yaml
- chart/voyager/templates/svc.yaml
- chart/voyager/values.yaml
- docs/user-guide/ingress/statefulset-pod.md
- hack/deploy/deployments.yaml
ref: https://github.com/kubernetes/charts/pull/953
> Apply various comments from official charts team

- docs/user-guide/ingress/README.md
- docs/user-guide/ingress/annotations.md
- docs/user-guide/ingress/weighted.md
- hack/example/weighted-backend/deployments.yaml
- pkg/controller/ingress/types.go
- pkg/controller/ingress/update.go
Format: `ingress.appscode.com/w1-w2-w3`
This mathces the format used by Kubernetes. https://github.com/kubernetes/kubernetes/blob/release-1.5/pkg/cloudprovider/providers/aws/aws.go#L79
> Use hyphen separated words as annotation key.

- pkg/controller/ingress/create.go
- pkg/controller/ingress/delete.go
- pkg/controller/ingress/handler.go
- pkg/controller/ingress/parser.go
- pkg/controller/ingress/resource.go
- pkg/controller/ingress/types.go
- pkg/controller/ingress/update.go
> Error out if Daemon type does not provide a node selector.

- pkg/controller/ingress/create.go
- test/e2e/e2e.go
- test/e2e/ingress.go
- test/e2e/serialized_tests.go
> Merge existing pods and service during create ingress resource

- hack/builddeps.sh
- hack/make.py
```
./hack/make.py test_deploy <provider>
```
> Disable analytics for test runs

- README.md
> Update version policy to point to client-go

- api/annotations.go
- pkg/ingress/create.go
@sadlil , do we need to update the label for existing pods?
Also fixes #161
> Update labels applied to HAProxy pods & services.

- api/annotations.go
- docs/user-guide/ingress/README.md
- pkg/ingress/create.go
- pkg/ingress/delete.go
- pkg/ingress/update.go
Also deletes previously created stats service.
> Stop creating stats service.

- hack/docker/voyager/setup.sh
This is required to read --config-file
> Use root user inside docker

- pkg/watcher/gc.go
- run.go
> Delete pods & services matching old labels before starting operator

- README.md
- api/extensions/certificate.yaml
- api/extensions/ingress.yaml
- api/register.go
- client/clientset/codec_test.go
- client/clientset/extensions.go
- docs/developer-guide/README.md
- docs/user-guide/README.md
- docs/user-guide/certificate/create.md
- docs/user-guide/ingress/README.md
- docs/user-guide/ingress/backend-rule.md
- docs/user-guide/ingress/external-svc.md
- docs/user-guide/ingress/header-rewrite.md
- docs/user-guide/ingress/named-virtual-hosting.md
- docs/user-guide/ingress/simple-fanout.md
- docs/user-guide/ingress/single-service.md
- docs/user-guide/ingress/source-range.md
- docs/user-guide/ingress/statefulset-pod.md
- docs/user-guide/ingress/stats-and-prometheus.md
- docs/user-guide/ingress/tcp.md
- docs/user-guide/ingress/tls.md
- docs/user-guide/ingress/weighted.md
- hack/deploy/test-ingress.yaml
- hack/example/ingress.yaml
- hack/example/weighted-backend/ingress.yaml
- test/e2e/ingress.go
I think we should go with networking.
> Change api group to networking.appscode.com

- docs/user-guide/ingress/replicas-and-autoscaling.md
> Add example with hpa

- api/ingress.go
- pkg/ingress/create.go
- pkg/ingress/delete.go
- pkg/ingress/parser.go
- pkg/ingress/resource.go
- pkg/ingress/resource_test.go
- pkg/ingress/types.go
- pkg/ingress/update.go
- pkg/operator/ingress_tprs.go
> Support setting resource for pods

- api/annotations.go
- api/annotations_test.go
- pkg/ingress/parser.go
- pkg/ingress/template/template.go
- pkg/ingress/types.go
- test/e2e/ingress.go
> Add configure option for Haproxy default timeout.

- docs/user-guide/ingress/README.md
- pkg/ingress/create.go
> Make node selectors options for HostPort

- pkg/operator/operator.go
- pkg/operator/servicemonitors.go
- pkg/util/kubernetes.go
> Recover ServiceMonitor

- glide.lock
- pkg/cmds/exporter.go
- pkg/cmds/exporter_handler.go
- pkg/cmds/run.go
- vendor/github.com/appscode/haproxy_exporter/exporter/haproxy_exporter.go
- vendor/github.com/spf13/cobra/command.go
- vendor/gopkg.in/yaml.v2/emitterc.go
- vendor/gopkg.in/yaml.v2/yamlh.go
> Add ingress label to exported metrics

- chart/voyager/templates/deployment.yaml
- hack/deploy/voyager-with-rbac.yaml
- hack/deploy/voyager-without-rbac.yaml
> Install Voyager as critical addon

- api/dns_resolver.go
- pkg/ingress/create.go
- pkg/ingress/parser.go
- pkg/operator/services.go
- test/e2e/ingress.go
Fixes #279 
Added Tests for redirection and RBAC.
> Fix External Service redirect Issue

- api/diff.go
- pkg/ingress/delete.go
- pkg/ingress/update.go
- test/e2e/ingress.go
> Fix Adding SSL to an existing ingress does not mount certs #260

- api/diff.go
- pkg/operator/ingress_tprs.go
> Correctly detect changed ports

- chart/voyager/README.md
- chart/voyager/templates/deployment.yaml
- chart/voyager/values.yaml
- hack/deploy/voyager-with-rbac.yaml
> Fix various chart issues

- api/annotations.go
- docs/user-guide/ingress/configure-timeouts.md
> Fix Implicit timeouts

- glide.lock
- pkg/cmds/exporter.go
- pkg/cmds/main.go
- pkg/cmds/run.go
- vendor/github.com/xenolf/lego/LICENSE
- vendor/github.com/xenolf/lego/acme/client.go
- vendor/github.com/xenolf/lego/acme/dns_challenge.go
- vendor/github.com/xenolf/lego/acme/http.go
- vendor/github.com/xenolf/lego/acme/messages.go
- vendor/github.com/xenolf/lego/providers/dns/dnsimple/dnsimple.go
- vendor/github.com/xenolf/lego/providers/dns/googlecloud/googlecloud.go
- vendor/github.com/xenolf/lego/providers/dns/rfc2136/rfc2136.go
- vendor/github.com/xenolf/lego/providers/dns/route53/route53.go
> Revendor lego

- glide.lock
- vendor/github.com/xenolf/lego/acme/dns_challenge.go
> Revendor lego to detect DNS zone correctly.

- api/diff.go
- api/port.go
- pkg/operator/ingress_tprs.go
> Detect port changes correctly.

- api/validator.go
- hack/deploy/on-master.yaml
- hack/make.py
- pkg/eventer/recorder.go
- pkg/ingress/controller.go
- pkg/ingress/create.go
- pkg/ingress/delete.go
- pkg/ingress/hostport.go
- pkg/ingress/loadbalancer.go
- pkg/ingress/nodeport.go
- pkg/ingress/parser.go
- pkg/ingress/rbac.go
- pkg/ingress/update.go
- pkg/operator/ingress_tprs.go
- pkg/operator/ingresses.go
- pkg/operator/nodes.go
- pkg/operator/operator.go
- pkg/operator/services.go
- pkg/operator/services_test.go
- third_party/forked/cloudprovider/cloud.go
- third_party/forked/cloudprovider/providers/aws/aws.go
- third_party/forked/cloudprovider/providers/azure/azure_firewall.go
- third_party/forked/cloudprovider/providers/gce/gce.go
> Revise ingress controller update operations	

- pkg/ingress/controller.go
- pkg/ingress/hostport.go
- pkg/ingress/loadbalancer.go
- pkg/ingress/nodeport.go
- pkg/ingress/update.go
- pkg/operator/ingress_tprs.go
- pkg/operator/services.go
This got reverted in #385 by mistake.
> Merge service and pod annotations

- third_party/forked/cloudprovider/providers/aws/aws.go
> Assign VoyagerCluster tag for Voyager Ingress

- client/clientset/certificate.go
- client/clientset/fake/certificate.go
- client/clientset/fake/ingress.go
- client/clientset/ingress.go
> Add Patch API Supports

- api/validator.go
- api/validator_test.go
> Fix Ingress validation error

- api/annotations.go
- pkg/ingress/nodeport.go
- pkg/ingress/parser.go
> Add ingress.appscode.com/accept-proxy annotation

- pkg/ingress/hostport.go
- pkg/ingress/loadbalancer.go
- pkg/ingress/nodeport.go
> Create RBAC objects if missing

- hack/docker/voyager/templates/stats.cfg
> Fix stats auth indentation when auth is omitted

- apis/voyager/ingress.go
- apis/voyager/v1beta1/ingress.go
- apis/voyager/v1beta1/zz_generated.conversion.go
- apis/voyager/v1beta1/zz_generated.deepcopy.go
- apis/voyager/zz_generated.deepcopy.go
- pkg/cmds/run.go
- pkg/ingress/hostport.go
- pkg/ingress/loadbalancer.go
- pkg/ingress/nodeport.go
- pkg/operator/gc.go
- Use Deployments from apps/v1beta1
Fixes #238 
Fixes #446
> Use Deployment for HostPort mode

- pkg/ingress/hostport.go
> Use DNSPolicy ClusterFirstWithHostNet for HostPort mode.

- apis/voyager/v1beta1/annotations.go
- pkg/ingress/hostport.go
- pkg/ingress/loadbalancer.go
- pkg/ingress/update.go
> Use svc.Spec.ExternalTrafficPolicy

- chart/voyager/README.md
- chart/voyager/templates/_helpers.tpl
- chart/voyager/templates/cluster-role-binding.yaml
- chart/voyager/templates/cluster-role.yaml
- chart/voyager/templates/deployment.yaml
- chart/voyager/templates/service-account.yaml
- chart/voyager/values.yaml
https://github.com/kubernetes/charts/pull/1533
> Update Chart RBAC format as recommended.

- apis/voyager/v1beta1/annotations.go
- hack/docker/voyager/templates/http-backend.cfg
- pkg/haproxy/types.go
- pkg/ingress/parser.go
- test/e2e/ingress_ops.go
Add support for `ingress.kubernetes.io/affinity` and `ingress.kuberne…tes.io/session-cookie-name`
> Add support for affinity annotations for ingress

- hack/docker/haproxy/1.7.6/setup.sh
- pkg/ingress/hostport.go
- pkg/ingress/loadbalancer.go
- pkg/ingress/nodeport.go
I also updated the flags in kloader.
https://github.com/appscode/kloader/blob/master/docs/reference/kloader_run.md
> Use kloader 4.0.0

- docs/reference/voyager_run.md
- pkg/cmds/run.go
- test/framework/configs.go
This is needed to use Kloader 4.0.0
> Change HAProxy image tag to 1.7.6-4.0.0-alpha.1

- apis/voyager/v1beta1/annotations.go
- hack/docker/voyager/templates/default-frontend.cfg
- hack/docker/voyager/templates/http-frontend.cfg
- pkg/haproxy/types.go
- pkg/ingress/parser.go
- test/e2e/ingress_ops.go
- test/framework/ingress_suite.go
- test/test-server/testserverclient/http.go
> Add Max Body size and CORS annotations

- glide.lock
- vendor/github.com/appscode/haproxy_exporter/exporter/haproxy_exporter.go
> Revendor haproxy-exporter

- apis/voyager/v1beta1/annotations.go
- hack/docker/voyager/templates/http-frontend.cfg
- pkg/haproxy/template_test.go
- pkg/haproxy/types.go
- pkg/ingress/parser.go
> Add hsts-max-age annotation

- pkg/ingress/controller.go
- pkg/ingress/hostport.go
- pkg/ingress/loadbalancer.go
- pkg/ingress/nodeport.go
> Add owner reference for Ingress

- pkg/certificate/controller.go
> Disable OCSP must staple

- chart/voyager/README.md
- chart/voyager/templates/deployment.yaml
- chart/voyager/values.yaml
- hack/deploy/with-rbac.yaml
- hack/deploy/without-rbac.yaml
> Install voyager operator as critical addon

- apis/voyager/v1beta1/annotations.go
- hack/docker/voyager/templates/http-frontend.cfg
- hack/docker/voyager/templates/tcp-frontend.cfg
- pkg/haproxy/template_test.go
- pkg/haproxy/types.go
- pkg/ingress/parser.go
- test/e2e/ingress_ops.go
- test/e2e/ingress_tcp.go
- test/framework/ingress_util.go
> Add whitelist-source-range annotation

- apis/voyager/v1beta1/annotations.go
- hack/docker/voyager/templates/defaults.cfg
- pkg/haproxy/template_test.go
- pkg/haproxy/types.go
- pkg/ingress/create.go
- pkg/ingress/hostport.go
- pkg/ingress/loadbalancer.go
- pkg/ingress/nodeport.go
- pkg/ingress/parser.go
- test/e2e/ingress_errorfiles.go
> Add errofiles annotation

- pkg/ingress/hostport.go
- pkg/ingress/loadbalancer.go
- pkg/ingress/nodeport.go
> Support static ip for Azure/ACS cluster.

- pkg/certificate/controller.go
#587
The order is important here.
> Inject well-known/acme-challenge path at the top of rules

- apis/voyager/v1beta1/diff.go
- chart/voyager/templates/deployment.yaml
- chart/voyager/templates/service.yaml
- docs/reference/voyager_run.md
- docs/user-guide/certificate/create-with-custom-provider.md
- docs/user-guide/certificate/create.md
- hack/deploy/with-rbac.yaml
- hack/deploy/without-rbac.yaml
- pkg/certificate/controller.go
- pkg/certificate/providers/http.go
- pkg/certificate/providers/http_test.go
- pkg/certificate/store.go
- pkg/cmds/run.go
- pkg/config/config.go
- pkg/operator/certificate_crds.go
> Fix HTTP challenger

- pkg/haproxy/template_test.go
- test/e2e/certificate_http.go
- test/e2e/ingress_errorfiles.go
- test/e2e/ingress_nodeport.go
- test/e2e/ingress_tcp.go
- test/e2e/ingress_tls.go
- test/e2e/ingress_updates.go
- test/test-server/server.go
> Use .test TLD

- docs/reference/voyager_run.md
- pkg/cmds/run.go
- pkg/config/config.go
- pkg/operator/certificate_crds.go
- pkg/operator/configmaps.go
- pkg/operator/daemonsets.go
- pkg/operator/deployments.go
- pkg/operator/endpoints.go
- pkg/operator/gc.go
- pkg/operator/ingress_crds.go
- pkg/operator/ingresses.go
- pkg/operator/nodes.go
- pkg/operator/operator.go
- pkg/operator/secret.go
- pkg/operator/servicemonitors.go
- pkg/operator/services.go
- pkg/operator/validator.go
> Allow restricting voyager in a single namespace

- pkg/certificate/acme_test.go
- pkg/certificate/controller_test.go
- pkg/haproxy/template_test.go
- pkg/ingress/hostport_test.go
- pkg/ingress/loadbalancer_test.go
- pkg/ingress/nodeport_test.go
Minor updates to fix `./hack/make.py test unit`.
> Update unit tests

- hack/docker/voyager/templates/tcp-frontend.cfg
> Fix tcp frontend template

- apis/voyager/v1beta1/annotations.go
- apis/voyager/v1beta1/validator.go
- docs/user-guide/ingress/README.md
- hack/example/e2e.yaml
- pkg/ingress/controller.go
- pkg/ingress/internal.go
- pkg/operator/nodes.go
> Implement `ingress.appscode.com/type: internal` 

- docs/reference/voyager_kloader_check.md
- docs/reference/voyager_kloader_run.md
- docs/reference/voyager_run.md
- docs/reference/voyager_tls-mounter.md
- glide.lock
- glide.yaml
- pkg/cmds/run.go
- pkg/cmds/tlsmounter.go
- pkg/config/config.go
- pkg/ingress/hostport.go
- pkg/ingress/internal.go
- pkg/ingress/loadbalancer.go
- pkg/ingress/nodeport.go
- pkg/tlsmounter/controller.go
- vendor/github.com/appscode/kloader/cmds/check.go
- vendor/github.com/appscode/kloader/cmds/root.go
- vendor/github.com/appscode/kloader/cmds/run.go
- vendor/github.com/appscode/kloader/cmds/util.go
> Raise kubernetes/client-go QPS and Burst config

- apis/voyager/v1beta1/port.go
- apis/voyager/v1beta1/validator.go
- hack/docker/voyager/templates/haproxy.cfg
- pkg/haproxy/types.go
- pkg/ingress/parser.go
> Enable TCP mode in port 80

- chart/voyager/templates/cluster-role.yaml
- hack/deploy/with-rbac.yaml
https://github.com/appscode/voyager/blob/c8f2995c88afcd683eff802eca24b9165387898c/pkg/ingress/delete.go#L26
> Add `deletecollection` permission to voyager operator

- apis/voyager/v1beta1/validator.go
- hack/deploy/openstack.sh
- pkg/ingress/loadbalancer.go
- pkg/ingress/rbac.go
- test/framework/ingress_util.go
> Support openstack provider

- apis/voyager/ingress.go
- apis/voyager/v1beta1/ingress.go
- apis/voyager/v1beta1/openapi_generated.go
- apis/voyager/v1beta1/zz_generated.conversion.go
- apis/voyager/v1beta1/zz_generated.deepcopy.go
- apis/voyager/zz_generated.deepcopy.go
- docs/reference/voyager_run.md
- pkg/cmds/run.go
- pkg/config/config.go
- pkg/ingress/create.go
- pkg/ingress/hostport.go
- pkg/ingress/internal.go
- pkg/ingress/loadbalancer.go
- pkg/ingress/nodeport.go
> Add ImagePullSecrets in Ingress

- chart/voyager/templates/NOTES.txt
- chart/voyager/templates/_helpers.tpl
- chart/voyager/templates/cluster-role-binding.yaml
- chart/voyager/templates/cluster-role.yaml
- chart/voyager/templates/deployment.yaml
- chart/voyager/templates/service-account.yaml
- chart/voyager/templates/service.yaml
ref:
- https://github.com/kubernetes/charts/issues/1785
- https://docs.helm.sh/chart_best_practices/#names-of-defined-templates
> Make chart namespaced

- hack/docker/voyager/templates/http-frontend.cfg
ref: https://github.com/appscode/voyager/issues/678
> Fix template rendering

- hack/docker/voyager/templates/default-backend.cfg
- hack/docker/voyager/templates/default-frontend.cfg
- hack/docker/voyager/templates/defaults.cfg
- hack/docker/voyager/templates/dns-resolver.cfg
- hack/docker/voyager/templates/haproxy.cfg
- hack/docker/voyager/templates/http-backend.cfg
- hack/docker/voyager/templates/http-frontend.cfg
- hack/docker/voyager/templates/tcp-backend.cfg
- hack/docker/voyager/templates/tcp-frontend.cfg
- hack/docker/voyager/templates/userlist.cfg
- pkg/haproxy/renderer.go
> Keep all newlines in haproxy.cfg

- pkg/ingress/controller.go
- pkg/ingress/parser.go
- pkg/ingress/parser_test.go
> Convert rules for SSL Passthrough

- pkg/ingress/parser.go
> Don't allow cross ns backend when voyager is restricted to own ns

- apis/voyager/v1beta1/diff.go
> Correctly handle updated ingress.class annotation

- pkg/ingress/parser.go
> Print namespace of missing service name

- pkg/certificate/controller.go
> Correctly encode cert for renewal.

- docs/guides/certificate/http.md
- pkg/certificate/controller.go
- pkg/haproxy/renderer.go
ref: https://github.com/appscode/voyager/issues/587#issuecomment-354123811
cc:@leonth
In 5.0.0-rc.x we started reordering paths to handle redirects properly. This means that acme well-known path has to be handled separately.
> Move Acme paths to top of path list

- apis/voyager/v1beta1/annotations.go
- hack/docker/voyager/templates/http-frontend.cfg
- pkg/haproxy/types.go
- pkg/ingress/parser.go
- test/e2e/ingress_ops.go
> Support additional CORS headers

- docs/guides/certificate/http.md
- docs/guides/certificate/providers.md
- docs/guides/certificate/route53.md
- docs/guides/ingress/README.md
- docs/guides/ingress/http/header-rewrite.md
- docs/guides/ingress/http/named-virtual-hosting.md
- docs/guides/ingress/http/simple-fanout.md
- docs/guides/ingress/security/tls-auth.md
- docs/guides/ingress/tcp/tcp.md
- docs/guides/ingress/tls/tls.md
I detected that in the voyager documentation are a lot of dead link and decided to fix that to make the usage of the voyager documentation easier.
The first commit is unverified because I didn't setup my git email properly initialy.
Please let me know if something is wrong or missing. Hope that helps.
> Update dead links

- hack/docker/voyager/templates/defaults.cfg
- hack/docker/voyager/templates/http-frontend.cfg
- pkg/haproxy/api/helper.go
- pkg/haproxy/api/helper_test.go
- pkg/haproxy/api/types.go
- pkg/haproxy/template/template_test.go
- pkg/ingress/parser.go
>  Removed maps from template data

- pkg/haproxy/api/types.go
> Checked nil backend before assigning

- pkg/cmds/run.go
> Removed panic in operator for bad-ingress

- apis/voyager/v1beta1/validator.go
- apis/voyager/v1beta1/validator_test.go
> Checked for invalid backend service name in validator

- pkg/certificate/acme.go
> Fix DNS-01 Challenge provider missing key in credential

- hack/docker/voyager/templates/http-frontend.cfg
- pkg/haproxy/template/template.go
Fixes #817
Fixes #813 
Fixes #818
> Revise host and path acl names to make them part of "api"

- apis/voyager/ingress.go
- apis/voyager/v1beta1/ingress.go
- apis/voyager/v1beta1/openapi_generated.go
- apis/voyager/v1beta1/validator_test.go
- apis/voyager/v1beta1/zz_generated.conversion.go
- apis/voyager/v1beta1/zz_generated.deepcopy.go
- apis/voyager/zz_generated.deepcopy.go
- docs/guides/ingress/configuration/backend-rule.md
- docs/guides/ingress/http/external-svc.md
- docs/guides/ingress/tls/aws-cert-manager.md
- pkg/ingress/parser.go
- test/e2e/ingress_backend.go
- test/e2e/ingress_dnsresolver.go
- test/e2e/ingress_ops.go
- test/e2e/ingress_tls.go
> Change BackendRule to BackendRules

- docs/setup/install.md
> Document GKE permission options

- hack/deploy/rbac-list.yaml
> Add missing RBAC for ServiceMonitor

- apis/voyager/v1beta1/dns_resolver.go
- apis/voyager/v1beta1/validator.go
> Checked timeout and dns-resolver maps

- apis/voyager/v1beta1/annotations.go
- apis/voyager/v1beta1/diff.go
- test/e2e/ingress_ops.go
- test/e2e/ingress_tls.go
> Fixed e2e tests

- chart/stable/voyager/README.md
- chart/stable/voyager/templates/apiregistration.yaml
- chart/stable/voyager/templates/deployment.yaml
- chart/stable/voyager/templates/service.yaml
- chart/stable/voyager/templates/validating-webhook-configuration.yaml
- chart/stable/voyager/values.yaml
- docs/setup/install.md
https://github.com/kubernetes-incubator/service-catalog/tree/master/charts/catalog
> Update charts to support api registration

- hack/docker/voyager/templates/http-frontend.cfg
> Remove bas acl from haproxy template

- chart/stable/voyager/Chart.yaml
- chart/stable/voyager/templates/user-roles.yaml
- hack/deploy/user-roles.yaml
- hack/deploy/voyager.sh
https://kubernetes.io/docs/admin/authorization/rbac/#aggregated-clusterroles
> Create user facing aggregate roles

- docs/setup/install.md
> Document user facing RBAC roles

- pkg/server/server.go
Fixes 2 bugs:
- Don't reinitialize storage.
- Ensure same hooks are used in postStart to ensure initialization
> Support multiple webhooks of same apiversion

- chart/stable/voyager/README.md
- chart/stable/voyager/templates/_helpers.tpl
- chart/stable/voyager/templates/apiregistration.yaml
- chart/stable/voyager/templates/cluster-role-binding.yaml
- chart/stable/voyager/templates/deployment.yaml
- chart/stable/voyager/templates/service-account.yaml
- chart/stable/voyager/values.yaml
https://github.com/kubernetes/helm/blob/master/docs/chart_best_practices/rbac.md
> Update chart to match RBAC best practices for charts

- pkg/haproxy/controller/ingress.go
- pkg/haproxy/controller/ingress_crd.go
ref: https://github.com/appscode/voyager/issues/889#issuecomment-370326939
> Stop using field selector in haproxy controller

- hack/deploy/voyager.sh
Signed-off-by: tamal <tamal@appscode.com>
> Enable RBAC by default in installer

- docs/setup/install.md
- docs/setup/uninstall.md
- hack/deploy/voyager.sh
Also uses removed finalizers before deleting crds. https://github.com/kubernetes/kubernetes/issues/60538
> Add --purge flag

- docs/concepts/ingress-types/loadbalancer.md
Fixes https://github.com/appscode/voyager/issues/930
> Document how to create internal LB in openstack

- docs/guides/ingress/tls/overview.md
> Mention how to handle wildcard domains in documentation

- pkg/haproxy/controller/certificate_crd.go
- pkg/haproxy/controller/configmap.go
- pkg/haproxy/controller/controller.go
- pkg/haproxy/controller/secret.go
- pkg/ingress/parser_test.go
- pkg/operator/configmaps.go
- pkg/operator/deployments.go
- pkg/operator/nodes.go
- pkg/operator/secret.go
- pkg/operator/servicemonitors.go
- pkg/operator/services.go
> Use correct queue for ingress

- test/e2e/ingress_errorfiles.go
> Fixed nodeport-errorfile test

- hack/deploy/voyager.sh
Fix https://github.com/appscode/voyager/issues/955
> Fix install instruction for minikube 0.24.x (Kube 1.8.0)

- docs/concepts/ingress-types/hostport.md
triple tilda quoting this line as I always have trouble copying it.
> hard to copy line

- apis/voyager/v1beta1/certificate.go
- apis/voyager/v1beta1/crd.go
- apis/voyager/v1beta1/crds.yaml
- apis/voyager/v1beta1/diff.go
- apis/voyager/v1beta1/ingress.go
- glide.lock
- glide.yaml
- hack/gencrd/main.go
- pkg/operator/ingress_crds.go
- pkg/operator/ingresses.go
- vendor/github.com/appscode/kutil/apiextensions/v1beta1/cli-utils.go
- vendor/github.com/appscode/kutil/apiextensions/v1beta1/convert_types.go
- vendor/github.com/appscode/kutil/apiextensions/v1beta1/crdvalidation.go
- vendor/github.com/appscode/kutil/apiextensions/v1beta1/kubernetes.go
- vendor/github.com/pkg/errors/stack.go
- vendor/github.com/spf13/cobra/command.go
- vendor/github.com/spf13/pflag/bytes.go
- vendor/github.com/spf13/pflag/count.go
- vendor/github.com/spf13/pflag/duration_slice.go
- vendor/github.com/spf13/pflag/flag.go
- vendor/github.com/spf13/pflag/int16.go
- vendor/github.com/spf13/pflag/string_array.go
- vendor/github.com/spf13/pflag/string_slice.go
- vendor/gopkg.in/ini.v1/LICENSE
- vendor/gopkg.in/ini.v1/file.go
- vendor/gopkg.in/ini.v1/ini.go
- vendor/gopkg.in/ini.v1/key.go
- vendor/gopkg.in/ini.v1/parser.go
- vendor/gopkg.in/ini.v1/section.go
- vendor/gopkg.in/ini.v1/struct.go
ref: https://kubernetes.io/docs/tasks/access-kubernetes-api/extend-api-custom-resource-definitions/#validation
> Add CRD Validation

- apis/voyager/v1beta1/annotations.go
- pkg/ingress/create.go
- pkg/ingress/hostport.go
- pkg/ingress/internal.go
- pkg/ingress/loadbalancer.go
- pkg/ingress/nodeport.go
- pkg/ingress/rbac.go
- test/framework/ingress_suite.go
> Use separate offshootLabels and offshootSelector

- docs/guides/ingress/security/oauth.md
https://github.com/appscodelabs/Dockerfiles/pull/13
> Use appscode/oauth2_proxy docker image 

- test/framework/ingress_util.go
> Fixed nodeport service url for minikube

- README.md
- docs/README.md
- hack/make.py
- pkg/ingress/create.go
- pkg/ingress/hostport.go
- pkg/ingress/internal.go
- pkg/ingress/loadbalancer.go
- pkg/ingress/nodeport.go
> Rename flag --analytics to --enable-analytics

- apis/voyager/v1beta1/certificate.go
- apis/voyager/v1beta1/ingress.go
- client/clientset/versioned/typed/voyager/v1beta1/certificate.go
- client/clientset/versioned/typed/voyager/v1beta1/fake/fake_certificate.go
- client/clientset/versioned/typed/voyager/v1beta1/fake/fake_ingress.go
- client/clientset/versioned/typed/voyager/v1beta1/ingress.go
- client/clientset/versioned/typed/voyager/v1beta1/util/certificate.go
- client/clientset/versioned/typed/voyager/v1beta1/util/ingress.go
This is done to support crds with or without spec/status split.
https://github.com/appscode/kutil/pull/151
> Add Update***Status helpers

- chart/stable/voyager/Chart.yaml
- chart/stable/voyager/README.md
- chart/stable/voyager/values.yaml
- docs/setup/install.md
> Update chart path for release-5.0

- .travis.yml
- pkg/haproxy/template/renderer.go
- pkg/haproxy/template/renderer_test.go
- pkg/ingress/parser.go
> Separated config-check from render-config

- docs/guides/ingress/configuration/ssl-passthrough.md
- pkg/ingress/parser_test.go
- test/e2e/ssl-passthrough.go
- test/e2e/tcp-sni.go
>  Updated doc for ssl-passthrough

- docs/guides/certificate/faq.md
> Use double quotes with `*`

- docs/guides/certificate/dns/route53.md
- Found this quite confusing and it seems this is the correct way around
> Fix ambiguous comment

- apis/voyager/v1beta1/crds.yaml
- apis/voyager/v1beta1/diff.go
- apis/voyager/v1beta1/ingress.go
- apis/voyager/v1beta1/openapi_generated.go
- apis/voyager/v1beta1/validator.go
- apis/voyager/v1beta1/validator_test.go
- apis/voyager/v1beta1/zz_generated.deepcopy.go
- hack/docker/voyager/templates/http-frontend.cfg
- openapi-spec/v2/swagger.json
- pkg/haproxy/api/types.go
- pkg/ingress/parser.go
- pkg/ingress/parser_test.go
> Support ALPN options in HTTP mode

- pkg/ingress/parser.go
> Correctly set port to binder

- hack/docker/oauth2-proxy/Dockerfile
- hack/docker/oauth2-proxy/build.sh
from https://github.com/appscodelabs/Dockerfiles/tree/0cca3339a0cf9b168c7efe69740f606d8cc0b5d3/oauth2-proxy
> Move oauth2-proxy image to Voyager repo

- apis/voyager/v1beta1/validator.go
- apis/voyager/v1beta1/validator_test.go
- docs/guides/ingress/security/oauth.md
- hack/docker/voyager/templates/http-frontend.cfg
- pkg/haproxy/api/types.go
- pkg/haproxy/template/template_test.go
- pkg/ingress/parser.go
> No auth-check for auth-backend-path itself

- pkg/cmds/server/options.go
Already assigned at:
https://github.com/appscode/voyager/blob/9c8521897ed549e82223013eac2da59668064851/pkg/cmds/server/options.go#L150
> Remove redundant assignment

- apis/voyager/v1beta1/annotations.go
- apis/voyager/v1beta1/conversion.go
- docs/guides/ingress/configuration/annotations.md
- docs/guides/ingress/pod-placement.md
> Support NodeSelector and Tolerations via annotation for std ingress

- docs/guides/ingress/security/basic-auth.md
- pkg/operator/services.go
- test/e2e/ingress_basicauth.go
>  Trigger update when service auth-annotations changed

- apis/voyager/v1beta1/annotations.go
- apis/voyager/v1beta1/validator.go
> Update timeout key list

- test/e2e/ingress_basicauth.go
> Added test for service auth annotation updates

- apis/voyager/v1beta1/validator.go
- docs/setup/install.md
- pkg/ingress/loadbalancer.go
> Add LoadBalancer type ingress support for DO and Linode

- docs/guides/ingress/security/oauth-github.md
- docs/guides/ingress/security/oauth-google.md
- docs/guides/ingress/security/oauth.md
> Document using Google oauth with Voyager

- apis/voyager/v1beta1/validator.go
- docs/setup/install.md
- hack/deploy/voyager.sh
- pkg/certificate/acme.go
- pkg/ingress/hostport.go
- pkg/ingress/loadbalancer.go
- pkg/ingress/nodeport.go
- test/framework/ingress_util.go
https://github.com/appscode/voyager/issues/1112
> Add support for aks

- hack/docker/voyager/templates/http-frontend.cfg
Fixes https://github.com/appscode/voyager/issues/1097
> Stop processing http request for LE well-known acme challenge path

- docs/guides/ingress/security/oauth-github.md
- docs/guides/ingress/security/oauth-google.md
- hack/docker/voyager/templates/http-frontend.cfg
> Forward X-Auth-Request headers in oauth

- docs/concepts/overview.md
- docs/guides/ingress/README.md
> Fix haproxy-stats page link

- chart/voyager/templates/cluster-role.yaml
- hack/deploy/rbac-list.yaml
> Fix rbac permissions for service monitors

- apis/voyager/v1beta1/diff.go
- pkg/operator/certificate_crds.go
> Get new LE account if user hits rate limits

- chart/voyager/templates/deployment.yaml
- hack/deploy/operator.yaml
This ensures that operator pod don't starve of cpu resource.
> Allocate cpu for operator pod.

- pkg/ingress/parser.go
> Parse tls-backend annotation for external service

- api/openapi-spec/swagger.json
- apis/voyager/v1beta1/certificate.go
- apis/voyager/v1beta1/crds.yaml
- apis/voyager/v1beta1/openapi_generated.go
- docs/guides/certificate/delete.md
- pkg/operator/certificate_crds.go
> Pause certificate checks

- apis/voyager/v1beta1/validator.go
Fixes build: https://travis-ci.org/appscode/voyager/jobs/394538024#L529
> Fix fmt string in validator

- docs/guides/ingress/configuration/annotations.md
- docs/guides/ingress/configuration/health-check.md
> Added docs for backend health check

- pkg/haproxy/api/helper.go
- pkg/haproxy/api/helper_test.go
- pkg/haproxy/api/types.go
- test/e2e/backend_name.go
> Fixed auto-generated backend names

- apis/voyager/v1beta1/crd.go
- chart/voyager/templates/deployment.yaml
- chart/voyager/values.yaml
- client/clientset/versioned/typed/voyager/v1beta1/util/certificate.go
- docs/reference/voyager_run.md
- docs/setup/install.md
- hack/deploy/operator.yaml
- hack/deploy/voyager.sh
- pkg/certificate/controller.go
- pkg/certificate/store.go
- pkg/cmds/server/options.go
- pkg/ingress/loadbalancer.go
xref: https://github.com/appscode/voyager/pull/1168
> Enable status subresource for voyager crds

- pkg/admission/plugin/admission.go
xref: https://github.com/appscode/voyager/issues/1161#issuecomment-400936467
> Throw validation error when LBType changes.

- chart/voyager/README.md
- chart/voyager/values.yaml
- docs/reference/voyager_run.md
- docs/setup/developer-guide/overview.md
- docs/setup/install.md
- hack/deploy/voyager.sh
- hack/dev-test.sh
- hack/docker/haproxy/1.8.12-alpine/Dockerfile
- hack/docker/haproxy/1.8.12-alpine/runit.sh
- hack/docker/haproxy/1.8.12-alpine/setup.sh
- hack/docker/haproxy/1.8.12-alpine/sv/haproxy-controller/run
- hack/docker/haproxy/1.8.12-alpine/sv/socklog-unix/run
- hack/docker/haproxy/1.8.12/Dockerfile
- hack/docker/haproxy/1.8.12/runit.sh
- hack/docker/haproxy/1.8.12/setup.sh
- hack/docker/haproxy/1.8.12/sv/haproxy-controller/run
- hack/docker/haproxy/1.8.12/sv/socklog-unix/run
- hack/docker/voyager/Dockerfile
- hack/docker/voyager/setup.sh
- hack/release.sh
- pkg/cmds/server/options.go
xref: https://github.com/appscode/voyager/issues/1173
> Use HAProxy 1.8.12

- hack/codegen.sh
- hack/concourse/test.sh
- hack/coverage.sh
- hack/deploy/voyager.sh
- hack/dev-run.sh
- hack/dev-test.sh
- hack/docker/haproxy/1.8.12-alpine/runit.sh
- hack/docker/haproxy/1.8.12-alpine/setup.sh
- hack/docker/haproxy/1.8.12/runit.sh
- hack/docker/haproxy/1.8.12/setup.sh
- hack/docker/voyager/setup.sh
```
find hack | grep sh | xargs shfmt -l -w -ci -i 2 {}
```
> Format shell scripts

- chart/voyager/README.md
- chart/voyager/templates/deployment.yaml
- chart/voyager/values.yaml
> Chart support for custom tolerations and affinity

- pkg/ingress/internal.go
- pkg/ingress/loadbalancer.go
- pkg/ingress/monitor.go
- pkg/ingress/nodeport.go
> Don't error out if old monitoring agent is missing

- docs/guides/ingress/configuration/keep-source-ip.md
> Document limited NLB support

- client/clientset/versioned/typed/voyager/v1beta1/util/certificate.go
- client/clientset/versioned/typed/voyager/v1beta1/util/ingress.go
- glide.lock
- vendor/github.com/appscode/kutil/util.go
- vendor/github.com/mitchellh/go-homedir/homedir.go
> Retry UpdateStatus calls

- api/crds/certificate.yaml
- api/crds/ingress.yaml
- hack/gencrd/main.go
> Enable status sub resource for crd yamls

- api/crds/ingress.yaml
- api/openapi-spec/swagger.json
- apis/voyager/v1beta1/ingress.go
- apis/voyager/v1beta1/openapi_generated.go
- apis/voyager/v1beta1/zz_generated.deepcopy.go
- pkg/ingress/hostport.go
- pkg/ingress/internal.go
- pkg/ingress/loadbalancer.go
- pkg/ingress/nodeport.go
> Support pod priority

- client/clientset/versioned/typed/voyager/v1beta1/util/certificate.go
- client/clientset/versioned/typed/voyager/v1beta1/util/ingress.go
xref: https://github.com/appscodelabs/discuss/issues/73
> Fix UpdateStatus helpers

- api/crds/certificate.yaml
- api/crds/ingress.yaml
- apis/voyager/v1beta1/crd.go
> Add categories

- chart/voyager/templates/cleaner.yaml
> Set serviceAccount for clearner job

- chart/voyager/README.md
- chart/voyager/templates/deployment.yaml
- chart/voyager/values.yaml
- hack/deploy/operator.yaml
> Support pod annotations in chart

- pkg/ingress/parser.go
> Touch custom errorfiles provided in configmap

- glide.lock
- glide.yaml
- vendor/github.com/appscode/kutil/meta/patch.go
> Use forked k8s.io/client-go v1.11.3

- hack/docker/haproxy/1.6.10/setup.sh
- hack/docker/haproxy/1.6.7/setup.sh
- hack/docker/haproxy/1.7.0/setup.sh
- hack/docker/haproxy/1.7.1/setup.sh
- hack/docker/haproxy/1.7.10/setup.sh
- hack/docker/haproxy/1.7.2/setup.sh
- hack/docker/haproxy/1.7.5/setup.sh
- hack/docker/haproxy/1.7.6/setup.sh
- hack/docker/haproxy/1.7.9/setup.sh
- hack/docker/haproxy/1.8.12-alpine/setup.sh
- hack/docker/haproxy/1.8.12/setup.sh
- hack/docker/haproxy/1.8.8-alpine/setup.sh
- hack/docker/haproxy/1.8.8/setup.sh
- hack/docker/haproxy/1.8.9-alpine/setup.sh
- hack/docker/haproxy/1.8.9/setup.sh
- hack/docker/voyager/setup.sh
- test/test-server/setup.sh
xref: https://github.com/appscodelabs/issues/issues/90
> Use --pull flag with docker build

- chart/voyager/README.md
- chart/voyager/templates/cleaner.yaml
- chart/voyager/values.yaml
> Support configuring cleaner image via vaules in chart

- chart/voyager/README.md
- chart/voyager/templates/cluster-role.yaml
- chart/voyager/templates/deployment.yaml
- chart/voyager/values.yaml
- docs/setup/install.md
- glide.lock
- glide.yaml
- hack/deploy/rbac-list.yaml
- pkg/operator/config.go
- pkg/operator/operator.go
- vendor/github.com/appscode/kutil/admissionregistration/v1beta1/kubernetes.go
- vendor/github.com/appscode/kutil/admissionregistration/v1beta1/mutatingwebhookconfiguration.go
- vendor/github.com/appscode/kutil/admissionregistration/v1beta1/validatingwebhookconfiguration.go
- vendor/github.com/appscode/kutil/core/v1/serviceaccount.go
- vendor/github.com/appscode/kutil/tools/watch/informerwatcher.go
- vendor/github.com/appscode/kutil/tools/watch/until.go
- vendor/github.com/appscode/kutil/util.go
> Enable webhooks by default in chart

- chart/voyager/templates/user-roles.yaml
- hack/deploy/user-roles.yaml
> Format user roles

- glide.lock
- pkg/cmds/server/start.go
- vendor/github.com/appscode/kutil/discovery/lib.go
- vendor/github.com/appscode/kutil/meta/cloud.go
- vendor/github.com/appscode/kutil/meta/incluster.go
- vendor/github.com/appscode/kutil/tools/analytics/analytics.go
- vendor/github.com/appscode/kutil/tools/clientcmd/client_config.go
- vendor/gopkg.in/ini.v1/file.go
- vendor/gopkg.in/ini.v1/ini.go
- vendor/gopkg.in/ini.v1/parser.go
> Use FQDN for kube-apiserver in AKS

- docs/reference/voyager.md
- docs/reference/voyager_check.md
- docs/reference/voyager_export.md
- docs/reference/voyager_haproxy-controller.md
- docs/reference/voyager_run.md
- docs/reference/voyager_version.md
- glide.lock
- glide.yaml
- pkg/cmds/server/start.go
- vendor/github.com/appscode/kutil/tools/clientcmd/client_config.go
> Update FixAKS helper

- chart/voyager/templates/cluster-role.yaml
- chart/voyager/templates/deployment.yaml
- glide.lock
- hack/deploy/operator.yaml
- hack/deploy/rbac-list.yaml
- pkg/eventer/recorder.go
- pkg/operator/config.go
- pkg/server/server.go
- vendor/github.com/appscode/kutil/admissionregistration/v1beta1/xray.go
- vendor/github.com/appscode/kutil/dynamic/kubernetes.go
- vendor/github.com/appscode/kutil/dynamic/unstructured.go
- vendor/github.com/go-openapi/jsonpointer/pointer.go
- vendor/k8s.io/apimachinery/pkg/util/jsonmergepatch/patch.go
> Write webhook xray event to operator workload

- glide.lock
- hack/deploy/voyager.sh
- vendor/github.com/appscode/kutil/admissionregistration/v1beta1/xray.go
- vendor/github.com/appscode/kutil/dynamic/kubernetes.go
> Detect failure quickly.

- chart/voyager/templates/validating-webhook.yaml
- hack/deploy/validating-webhook.yaml
> Set SideEffects to None for webhooks

- api/crds/ingress.yaml
- apis/voyager/v1beta1/crd.go
> Fix Ingress column header

- pkg/ingress/controller.go
- pkg/operator/gc.go
- test/framework/ingress_suite.go
- test/framework/ingress_util.go
Fixing missed api calls from https://github.com/appscode/voyager/pull/1221
> Only use apps/v1 apigroup from controller.

- chart/voyager/templates/cluster-role.yaml
- glide.lock
- glide.yaml
- hack/deploy/rbac-list.yaml
- hack/deploy/voyager.sh
- pkg/ingress/controller.go
- pkg/ingress/hostport_test.go
- pkg/ingress/loadbalancer_test.go
- pkg/ingress/nodeport_test.go
- pkg/ingress/rbac.go
- pkg/server/server.go
- vendor/github.com/appscode/kutil/admissionregistration/v1beta1/mutatingwebhookconfiguration.go
- vendor/github.com/appscode/kutil/admissionregistration/v1beta1/validatingwebhookconfiguration.go
- vendor/github.com/appscode/kutil/admissionregistration/v1beta1/xray.go
- vendor/github.com/appscode/kutil/apiregistration/v1beta1/apiservice.go
- vendor/github.com/appscode/kutil/apiregistration/v1beta1/kubernetes.go
- vendor/github.com/appscode/kutil/dynamic/kubernetes.go
> Fix upgrade flow for installer script

- glide.lock
- hack/deploy/voyager.sh
- pkg/server/server.go
- vendor/github.com/appscode/kutil/admissionregistration/v1beta1/mutatingwebhookconfiguration.go
- vendor/github.com/appscode/kutil/admissionregistration/v1beta1/validatingwebhookconfiguration.go
- vendor/github.com/appscode/kutil/admissionregistration/v1beta1/xray.go
> Handle ErrCallingWebhook in xray

- glide.lock
- vendor/github.com/appscode/kutil/admissionregistration/v1beta1/xray.go
> Fix webhook xray checker

- docs/setup/install.md
- glide.lock
- hack/deploy/operator.yaml
- hack/deploy/voyager.sh
- vendor/github.com/appscode/kutil/admissionregistration/v1beta1/xray.go
> Expose flags to installer script

- chart/voyager/templates/cleaner.yaml
> Pass image pull secrets for cleaner job in chart

- chart/voyager/README.md
- chart/voyager/templates/deployment.yaml
- chart/voyager/values.yaml
> Expose flags to chart

- glide.lock
- hack/gendocs/main.go
- main.go
- pkg/cmds/haproxy.go
- pkg/cmds/root.go
- pkg/cmds/run.go
- pkg/config/config.go
- pkg/ingress/create.go
- pkg/ingress/hostport.go
- pkg/ingress/internal.go
- pkg/ingress/loadbalancer.go
- pkg/ingress/nodeport.go
- test/e2e/e2e.go
- vendor/github.com/appscode/kutil/tools/cli/cli.go
- vendor/github.com/appscode/kutil/tools/clientcmd/client_config.go
- vendor/github.com/golang/snappy/decode.go
- vendor/github.com/golang/snappy/decode_amd64.go
- vendor/github.com/golang/snappy/decode_amd64.s
- vendor/github.com/golang/snappy/decode_other.go
- vendor/github.com/golang/snappy/encode.go
- vendor/github.com/golang/snappy/encode_amd64.go
- vendor/github.com/golang/snappy/encode_amd64.s
- vendor/github.com/golang/snappy/encode_other.go
- vendor/github.com/golang/snappy/snappy.go
- vendor/github.com/hashicorp/go-retryablehttp/client.go
> Set periodic analytics

- apis/voyager/v1beta1/validator.go
- apis/voyager/v1beta1/validator_test.go
- pkg/ingress/parser.go
- test/e2e/ingress_named_service_port.go
> Add support for named service port

- docs/guides/certificate/dns/providers.md
- glide.lock
- pkg/certificate/acme.go
- vendor/github.com/xenolf/lego/providers/dns/gandiv5/client.go
- vendor/github.com/xenolf/lego/providers/dns/gandiv5/gandiv5.go
> Add support for Gandi V5 acme dns provider

- hack/deploy/voyager.sh
xref: https://github.com/appscodelabs/discuss/issues/130
> Fix the case for deploying using MINGW64 for windows

- hack/deploy/voyager.sh
Fixes https://github.com/appscode/voyager/issues/1332
> Use onessl 0.10.0

- hack/deploy/operator.yaml
- hack/deploy/voyager.sh
> Don't use priority class when operator namespace is not kube-system

- chart/voyager/templates/deployment.yaml
xref: https://github.com/appscodelabs/discuss/issues/126
> Pass Annotations to Operator PodTemplate

- docs/CHANGELOG.md
> Update changelog for 9.0.0

- docs/setup/developer-guide/overview.md
- test/e2e/backend_service.go
- test/framework/ingress_suite.go
- test/framework/ingress_util.go
> Fix e2e test for empty backend

- docs/guides/ingress/configuration/http-2.md
> Fix hugo frontmatter for HTTP/2 doc

- README.md
> Release 9.0.0

- docs/guides/certificate/faq.md
> Update LE certificate renewal buffer info

- chart/voyager/README.md
- chart/voyager/values.yaml
- docs/reference/voyager_run.md
- docs/setup/developer-guide/overview.md
- docs/setup/install.md
- hack/concourse/test.sh
- hack/concourse/uninstall.sh
- hack/deploy/voyager.sh
- hack/dev-test.sh
- hack/docker/haproxy/1.9.4-alpine/Dockerfile
- hack/docker/haproxy/1.9.4-alpine/runit.sh
- hack/docker/haproxy/1.9.4-alpine/setup.sh
- hack/docker/haproxy/1.9.4-alpine/sv/haproxy-controller/run
- hack/docker/haproxy/1.9.4-alpine/sv/socklog-unix/run
- hack/docker/haproxy/1.9.4/Dockerfile
- hack/docker/haproxy/1.9.4/runit.sh
- hack/docker/haproxy/1.9.4/setup.sh
- hack/docker/haproxy/1.9.4/sv/haproxy-controller/run
- hack/docker/haproxy/1.9.4/sv/socklog-unix/run
- hack/docker/voyager/Dockerfile
- hack/docker/voyager/setup.sh
- hack/release.sh
- pkg/cmds/server/options.go
- Added `v1.9.4` branch https://github.com/appscode/haproxy-auth-request/tree/v1.9.4
> Update haproxy version to 1.9.4

- chart/voyager/README.md
- chart/voyager/values.yaml
- docs/reference/voyager_run.md
- docs/setup/developer-guide/overview.md
- docs/setup/install.md
- hack/concourse/test.sh
- hack/concourse/uninstall.sh
- hack/deploy/voyager.sh
- hack/dev-test.sh
- hack/docker/haproxy/1.9.6-alpine/Dockerfile
- hack/docker/haproxy/1.9.6-alpine/runit.sh
- hack/docker/haproxy/1.9.6-alpine/setup.sh
- hack/docker/haproxy/1.9.6-alpine/sv/haproxy-controller/run
- hack/docker/haproxy/1.9.6-alpine/sv/socklog-unix/run
- hack/docker/haproxy/1.9.6/Dockerfile
- hack/docker/haproxy/1.9.6/runit.sh
- hack/docker/haproxy/1.9.6/setup.sh
- hack/docker/haproxy/1.9.6/sv/haproxy-controller/run
- hack/docker/haproxy/1.9.6/sv/socklog-unix/run
- hack/docker/voyager/Dockerfile
- hack/docker/voyager/setup.sh
- hack/release.sh
- pkg/cmds/server/options.go
Added `v1.9.6` branch https://github.com/appscode/haproxy-auth-request/tree/v1.9.6
Fixes #1362
> Update haproxy version to 1.9.6

- docs/guides/ingress/security/oauth-dashboard.md
- docs/guides/ingress/security/oauth-github.md
- docs/guides/ingress/security/oauth-google.md
- hack/docker/voyager/templates/http-frontend.cfg
> Get id-token from Authorization header

- docs/reference/voyager.md
- docs/reference/voyager_check.md
- docs/reference/voyager_export.md
- docs/reference/voyager_haproxy-controller.md
- docs/reference/voyager_run.md
- docs/reference/voyager_version.md
- hack/gendocs/main.go
> Use absolute path as aliases for reference docs

- docs/examples/monitoring/coreos-operator/demo-0.yaml
- docs/guides/ingress/configuration/config-volumes.md
- docs/guides/ingress/configuration/health-check.md
- docs/guides/ingress/configuration/http-2.md
- docs/guides/ingress/http/blue-green-deployment.md
- docs/guides/ingress/http/statefulset-pod.md
- docs/guides/ingress/scaling.md
- docs/guides/ingress/security/oauth-dashboard.md
- docs/guides/ingress/security/oauth-github.md
- docs/guides/ingress/security/oauth-google.md
- go.mod
- go.sum
- hack/example/e2e.yaml
- hack/example/weighted-backend/deployments.yaml
- vendor/kmodules.xyz/webhook-runtime/client/workload/v1/factory.go
- vendor/modules.txt
- Updated `kmodules/webhook-runtime` to apps/v1 and updated go.mod here
- Fixed all .yaml files by updating to apps/v1
> Update .yaml apps/v1 and Update Vendor to Fix DaemonSet Issue 

- chart/voyager/templates/apiregistration.yaml
- chart/voyager/templates/cluster-role-binding.yaml
- chart/voyager/templates/cluster-role.yaml
- chart/voyager/templates/deployment.yaml
- chart/voyager/templates/user-roles.yaml
- chart/voyager/values.yaml
- docs/guides/certificate/dns/google-cloud.md
- docs/guides/certificate/dns/route53.md
- docs/guides/certificate/http/overview.md
- docs/guides/ingress/pod-placement.md
- docs/reference/voyager_run.md
- docs/setup/developer-guide/overview.md
- docs/setup/install.md
- hack/deploy/operator.yaml
- hack/deploy/use-custom-tpl.yaml
- hack/deploy/voyager.sh
- pkg/cmds/server/options.go
- pkg/config/config.go
- pkg/ingress/controller.go
- pkg/ingress/hostport.go
- pkg/ingress/hostport_test.go
- pkg/ingress/internal.go
- pkg/ingress/loadbalancer.go
- pkg/ingress/loadbalancer_test.go
- pkg/ingress/nodeport.go
- pkg/ingress/nodeport_test.go
- test/e2e/ingress_rbac.go
> Remove --rbac flag

- Makefile
- hack/build.sh
- hack/fmt.sh
- hack/test.sh
> Add license header for Makefile

- docs/guides/ingress/README.md
- docs/guides/ingress/avoid-503-with-server-graceful-shutdown.md
- docs/guides/ingress/graceful-reload.md
- Add detailed doc about avoiding 503 with server graceful shutdown
> Avoid 503 Error Doc

- docs/guides/certificate/dns/google-cloud.md
I followed this guide to change scopes and it works well. Thought I help out with a pr.
> How to change scopes on a running kubernetes cluster.

- hack/deploy/voyager.sh
> Download onessl version v0.13.1 for Kubernetes 1.16 fix

- chart/voyager/templates/deployment.yaml
Just followed up on the note from @nterry
https://github.com/appscode/voyager/issues/1438
It fixes the helm install error.
> Fix helm chart install v11.0.1

- charts/voyager/templates/cleaner.yaml
- hack/deploy/voyager.sh
> Properly handle empty image pull secret name in installer

- go.mod
- go.sum
- pkg/ingress/controller.go
- pkg/ingress/create.go
- pkg/ingress/hostport.go
- pkg/ingress/internal.go
- pkg/ingress/loadbalancer.go
- pkg/ingress/nodeport.go
- pkg/ingress/rbac.go
- vendor/kmodules.xyz/client-go/CONTRIBUTING.md
- vendor/kmodules.xyz/client-go/core/v1/kubernetes.go
- vendor/kmodules.xyz/client-go/discovery/lib.go
- vendor/kmodules.xyz/client-go/dynamic/kubernetes.go
- vendor/kmodules.xyz/monitoring-agent-api/agents/agents.go
- vendor/kmodules.xyz/monitoring-agent-api/api/v1/types.go
- vendor/modules.txt
> Use OwnerReference helpers from kmodules

- apis/voyager/v1beta1/annotations.go
> Fix typo for APISchemaIngress

- .github/workflows/ci.yml
- Makefile
- charts/voyager/README.md
- charts/voyager/templates/cleaner.yaml
- charts/voyager/templates/cluster-role.yaml
- charts/voyager/templates/deployment.yaml
- charts/voyager/templates/service-account.yaml
- charts/voyager/values.yaml
- Use helmpack/chart-testing:v3.0.0-beta.1
- Use charts in make install commands
- Cleanup orphaned apiservices
- Pass imagePullSecrets via service account
> Various fixes to chart

- charts/voyager/README.md
- charts/voyager/templates/deployment.yaml
- charts/voyager/templates/validating-webhook.yaml
- docs/concepts/ingress-types/hostport.md
- docs/concepts/ingress-types/internal.md
- docs/concepts/ingress-types/loadbalancer.md
- docs/concepts/ingress-types/nodeport.md
- docs/guides/certificate/dns/google-cloud.md
- docs/guides/certificate/dns/route53.md
- docs/guides/certificate/http/overview.md
- docs/guides/ingress/configuration/custom-templates.md
- docs/guides/ingress/pod-placement.md
- docs/setup/install.md
- docs/setup/uninstall.md
- Add helm 3 instructions
- Remove script installer instructions
> Update installation instructions

- test/e2e/agent_check_test.go
- test/e2e/ingress_default_test.go
- test/e2e/ingress_dnsresolver_test.go
- test/e2e/ingress_hostport_test.go
- test/e2e/ingress_ops_test.go
- test/framework/ingress_util.go
> Fix failed e2e tests

- README.md
- api/openapi-spec/swagger.json
- charts/voyager/Chart.yaml
- charts/voyager/README.md
- charts/voyager/values.yaml
- docs/CHANGELOG.md
- hack/gencrd/main.go
- hack/gendocs/main.go
- pkg/cmds/server/options.go
> Prepare release v12.0.0-rc.0

- docs/CHANGELOG.md
- docs/setup/install.md
- docs/setup/uninstall.md
> Fix css class for helm 3 tab

- pkg/ingress/loadbalancer.go
Regression was introduced in #1448 . Fixes #1471
> Exit only if UpdateStatus returns error.

- README.md
- api/openapi-spec/swagger.json
- charts/voyager/Chart.yaml
- charts/voyager/README.md
- charts/voyager/values.yaml
- docs/CHANGELOG.md
- hack/gencrd/main.go
- hack/gendocs/main.go
- pkg/cmds/server/options.go
> Prepare v12.0.0-rc.1

- .github/workflows/ci.yml
- docs/reference/voyager_run.md
- docs/reference/voyager_version.md
- hack/gendocs/main.go
- hack/kubernetes/kind-1.11.yaml
> Refactor CI pipeline to build once.

- charts/voyager/README.md
- charts/voyager/templates/apiregistration.yaml
- charts/voyager/values.yaml
> Allow specifying rather than generating certs

- charts/voyager/README.md
- charts/voyager/templates/deployment.yaml
- charts/voyager/values.yaml
Signed-off-by: Salvatore Mazzarino <dev@mazzarino.cz>
Add a flag to restrict the blast radius of the operator.
> Add restrict-to-operator-namespace flag

- charts/voyager/templates/cluster-role.yaml
ref: https://github.com/appscode/voyager/pull/1482#pullrequestreview-400049110
> Add rbac permissions for statefulset

- hack/coverage.sh
- hack/docker/haproxy/1.6.10/setup.sh
- hack/docker/haproxy/1.6.7/setup.sh
- hack/docker/haproxy/1.7.0/setup.sh
- hack/docker/haproxy/1.7.1/setup.sh
- hack/docker/haproxy/1.7.10/setup.sh
- hack/docker/haproxy/1.7.2/setup.sh
- hack/docker/haproxy/1.7.5/setup.sh
- hack/docker/haproxy/1.7.6/setup.sh
- hack/docker/haproxy/1.7.9/setup.sh
- hack/docker/haproxy/1.8.12-alpine/setup.sh
- hack/docker/haproxy/1.8.12/setup.sh
- hack/docker/haproxy/1.8.8-alpine/setup.sh
- hack/docker/haproxy/1.8.8/setup.sh
- hack/docker/haproxy/1.8.9-alpine/setup.sh
- hack/docker/haproxy/1.8.9/setup.sh
- hack/docker/haproxy/1.9.15-alpine/setup.sh
- hack/docker/haproxy/1.9.15/setup.sh
- hack/docker/haproxy/1.9.2-alpine/setup.sh
- hack/docker/haproxy/1.9.2/setup.sh
- hack/docker/haproxy/1.9.4-alpine/setup.sh
- hack/docker/haproxy/1.9.4/setup.sh
- hack/docker/haproxy/1.9.6-alpine/setup.sh
- hack/docker/haproxy/1.9.6/setup.sh
- hack/release.sh
> Use BASH_SOURCE to calculate $REPO_ROOT

- Makefile
- client/clientset/versioned/typed/voyager/v1beta1/util/certificate.go
- client/clientset/versioned/typed/voyager/v1beta1/util/ingress.go
- go.mod
- go.sum
- pkg/certificate/controller.go
- pkg/certificate/store.go
- pkg/ingress/loadbalancer.go
- vendor/kmodules.xyz/client-go/Makefile
- vendor/kmodules.xyz/client-go/apiextensions/v1beta1/convert_types.go
- vendor/kmodules.xyz/client-go/apiextensions/v1beta1/crdvalidation.go
- vendor/kmodules.xyz/client-go/apiextensions/v1beta1/kubernetes.go
- vendor/kmodules.xyz/client-go/discovery/lib.go
- vendor/kmodules.xyz/client-go/go.mod
- vendor/modules.txt
> Fix Update***Status helpers

- README.md
- api/openapi-spec/swagger.json
- hack/gencrd/main.go
- pkg/cmds/server/options.go
> Prepare release v13.0.0-beta.0

- README.md
- api/openapi-spec/swagger.json
- hack/gencrd/main.go
- pkg/cmds/server/options.go
> Prepare release v13.0.0-beta.1

- api/openapi-spec/swagger.json
> Update repository config

- docs/CHANGELOG-v2021.09.15.md
Release: v2021.09.15
Release-tracker: https://github.com/voyagermesh/CHANGELOG/pull/7
> Prepare for release v2021.09.15

- docs/reference/cli/voyager.md
- docs/reference/cli/voyager_check.md
- docs/reference/cli/voyager_completion.md
- docs/reference/cli/voyager_convert.md
- docs/reference/cli/voyager_version.md
> Update docs for voyagermesh/cli@696408d5

- docs/CHANGELOG-v2022.08.17.md
Release: v2022.08.17
Release-tracker: https://github.com/voyagermesh/CHANGELOG/pull/20
> Prepare for release v2022.08.17

- .github/workflows/ci.yml
- .github/workflows/preview-website.yml
> Use Go 1.19

- .github/workflows/ci.yml
- .github/workflows/preview-website.yml
> Update wrokflows (Go 1.20, k8s 1.26)

- .github/workflows/preview-website.yml
> Use Go 1.22

- docs/reference/cli/voyager.md
- docs/reference/cli/voyager_check.md
- docs/reference/cli/voyager_completion.md
- docs/reference/cli/voyager_convert.md
- docs/reference/cli/voyager_version.md
> Update docs for voyagermesh/cli@99baac84

- .github/workflows/ci.yml
- .github/workflows/preview-website.yml
- .github/workflows/release-tracker.yml
> Use Go 1.23

- .github/workflows/preview-website.yml
> Use Go 1.24

- .github/workflows/preview-website.yml
> Use Go 1.25
