voyagermesh/voyager

test/e2e/ingress.go
Only Daemon Mode needs retry in test. It needs some time to EnsureFirewall(). There is no way to determine when this is done. So retry for a amount of time.
Service: Loadbalacner do not need this because, that get the IP after everything is initiated.
=> Add Retry on DaemonMode Loadbalancer http test call

hack/chart/voyager/Chart.yaml, hack/chart/voyager/README.md, hack/chart/voyager/templates/NOTES.txt, hack/chart/voyager/templates/_helpers.tpl, hack/chart/voyager/templates/deployment.yaml, hack/chart/voyager/values.yaml
```
NAME:   brazil
LAST DEPLOYED: Fri Apr 21 18:01:55 2017
NAMESPACE: sauman
STATUS: DEPLOYED
RESOURCES:
==> extensions/v1beta1/Deployment
NAME            DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
voyager-brazil  1        1        1           1          6s
NOTES:
Set cloudProvider, clustername for installing voyager
To verify that voyager controller has started, run:
kubectl --namespace=sauman get deployments -l "release=brazil, run=voyager-brazil"
```
=> Fix stable chart

docs/user-guide/component/ingress/README.md, docs/user-guide/component/ingress/statefulset-pod.md, hack/make.py, pkg/controller/ingress/parser.go, pkg/controller/ingress/parser_test.go, test/e2e/ingress.go, test/e2e/test_ingress_values.go, test/test-server/server.go, test/test-server/setup.sh, test/test-server/testserverclient/http.go, test/test-server/yaml/controller.yaml, vendor/github.com/appscode/k8s-addons/api/voyager_types.go
Fixes #14
cc @skuda, This should fix your scenario.
=> Ingress Hostname based traffic forwarding

pkg/controller/ingress/resource.go, test/e2e/ingress.go, test/e2e/ingress_testsuit.go, test/e2e/test_ingress_values.go
Do not restart lb pod when backend pod restarts, Fixes #69
```
mysql-user-0                           2/2       Running   0          29s
mysql-user-1                           2/2       Running   0          4m
voyager-mysql-user-ingress-s3p3f       1/1       Running   0          4m
```
=> Do not restart lb pod when backend pod restarts

pkg/controller/ingress/template/template.go
Ref:
- https://timtaubert.de/blog/2014/11/the-sad-state-of-server-side-tls-session-resumption-implementations/
- https://gist.github.com/rnewson/8384304
#32
=> Ensure forward secrecy

pkg/controller/ingress/create.go, pkg/controller/ingress/delete.go, pkg/controller/ingress/parser.go, pkg/controller/ingress/resource.go, pkg/controller/ingress/types.go, pkg/controller/ingress/update.go
- NodePort mode: In `NodePort` mode, a `NodePort` service will be used to expose HAProxy. No Firewall in configured. Fixes #68 
- Adds `ingress.appscode.com/replicas` annotation so users can set # of replicas for HAProxy pods.
- Renamed `ingress.appscode.com/loadbalancer.persist` to `ingress.appscode.com/persist`.
- Use Deployment to create HAProxy pods instead of RC. This is important, since replicas > 1
=> Introduce NodePort mode

docs/user-guide/component/ingress/tcp.md
Ingress spec uses port `9898` whereas documentation specified `9899`
=> tcp.md: fix typo/port mismatch

pkg/controller/ingress/create.go, pkg/controller/ingress/delete.go, pkg/controller/ingress/resource.go, pkg/controller/ingress/resource_test.go, pkg/controller/ingress/types.go, pkg/controller/ingress/update.go, test/e2e/ingress.go, test/e2e/ingress_testsuit.go, test/e2e/serialized_tests.go, test/e2e/test_ingress_values.go, test/e2e/utils.go, test/testframework/test_context.go, vendor/github.com/appscode/errors/types.go
This PR significantly reduced test run time by at least **one third**. Uses concurrency.
@ashiquzzaman33 
There is now two extra flag to control test namespace and test concurrency.  
`-namespace` needs to be provided while testing. The value of the flag must needs to be prefixed with **test-**. otherwise test will not run. I suggest create a `ns` as test-timestamp provide this value as flag. and remove when test is done.
`-max-test` will control how many test will run at once concurrently. The default value is 5. If you have a High node cluster, i suggest you can increase it.
=> Improve test framework

cmd/voyager/app/daemon.go, cmd/voyager/app/options/options.go, cmd/voyager/app/watcher.go, cmd/voyager/main.go, pkg/analytics/analytics.go
=> Collect analytics for voyager usages

docs/user-guide/ingress/README.md, pkg/controller/ingress/create.go, pkg/controller/ingress/parser.go, pkg/controller/ingress/types.go, pkg/controller/ingress/update.go, test/e2e/serialized_tests.go, test/e2e/utils.go
BREAKING: annotation key renamed from `ingress.appscode.com/daemon.nodeSelector` to `ingress.appscode.com/daemon.nodeSelector`.
=> Make nodeSelector annotation applicable for any more.

pkg/controller/ingress/create.go, pkg/controller/ingress/handler.go, pkg/controller/ingress/parser.go, pkg/controller/ingress/template/template.go, pkg/controller/ingress/types.go, pkg/controller/ingress/update.go, test/e2e/ingress.go
This preserves source IP for LoadBalancer type ingresses  for aws, gce, gke, azure. The actual configuration generated depends on the underlying cloud provider.
- gce, gke, azure: Adds annotation service.beta.kubernetes.io/external-traffic: OnlyLocal
to services used to expose HAProxy.
ref: https://kubernetes.io/docs/tutorials/services/source-ip/#source-ip-for-services-with-typeloadbalancer
- aws: Enforces the use of the PROXY protocol over any connection accepted by any of
the sockets declared on the same line. Versions 1 and 2 of the PROXY protocol
are supported and correctly detected. The PROXY protocol dictates the layer
3/4 addresses of the incoming connection to be used everywhere an address is
used, with the only exception of "tcp-request connection" rules which will
only see the …
=> Use ingress.appscode.com/keep-source-ip: true to preserve source IP

run.go
This conflicts with the -h (help) flag
=> Stop redefining -h flag for run command.

pkg/ingress/create.go, pkg/ingress/handler.go, pkg/ingress/parser.go, pkg/ingress/types.go, pkg/ingress/update.go
=> Support AWS cert manager

exporter.go, exporter_handler.go, main.go, pkg/analytics/analytics.go, run.go
ref : #154 
This is fast part of running voyager as side-car exporter. URL structure for metrics is changed from 
`/%s/v1beta1/namespaces/%s/ingresses/%s/pod/%s/metrics` --->
`/%s/v1beta1/namespaces/%s/ingresses/%s/metrics?pod=<ip>`
If pod is missing, ip is considered 127.0.0.1
=> Add voyager export command

api/annotations.go, api/monitor.go, chart/voyager/templates/deployment.yaml, chart/voyager/templates/svc.yaml, docs/user-guide/README.md, docs/user-guide/ingress/README.md, docs/user-guide/ingress/external-svc.md, docs/user-guide/ingress/stats-and-metrics.md, hack/deploy/deployments.yaml, pkg/certificates/providers/http.go, pkg/certificates/providers/http_test.go, run.go
- 56789: Default stats port (Previously 1936)
- 56790: Default exporter port. Also the port used by operator to expose its own metrics.
- 56791: HTTP port used with ACME HTTP challenge (Previously 56789)
=> Update default ports

pkg/ingress/create.go, pkg/ingress/handler.go, pkg/ingress/parser.go, pkg/ingress/types.go, pkg/ingress/update.go
cc: @julianvmodesto 
Fixes #189
=> Open both port 443 & 80 when AWS cert manager is in use.

hack/docker/haproxy/1.7.6/runit.sh
Manual testing shows HAProxy don't mind the extra newline.
=> Add a newline between crt & key.

README.md
The contribution guide link is broken, so I fix it.
=> fix the contribution guild link (#274)

api/diff.go, chart/voyager/templates/cluster-role.yaml, hack/deploy/voyager-with-rbac.yaml, pkg/cmds/run.go, pkg/ingress/create.go, pkg/ingress/delete.go, pkg/ingress/rbac.go, pkg/ingress/update.go, pkg/operator/ingress_tprs.go, test/e2e/ingress.go, test/testframework/test_context.go
=> Fix RBAC configs

third_party/forked/cloudprovider/providers/aws/aws.go, third_party/forked/cloudprovider/providers/aws/regions.go
fixes #281 
I hit this issue while trying to create an AppsCode Ingress using `NodePort` as well. Digging into the code, the tests are a little false-y in that an earlier test would call `newAWSCloud()` which would call `RecognizeWellKnownRegions()` and then any future tests would benefit from the well known regions getting loaded. This is obviously not the normal scenario when running the controller in a real world environment where the first invocation of `newAWSCloud()` would perform the `isValidRegion()` check prior to any regions being loaded.
I wasn't sure if the call to `awscredentialprovider.RegisterCredentialsProvider(region)` in `regions.go` was really necessary (i.e. being used) because it's the primary culprit for making sure a region is only loaded a single time due to …
=> move RecognizeWellKnownRegions() to the beginning of newAWSCloud()

pkg/ingress/create.go
Fixes #320 
ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#inter-pod-affinity-and-anti-affinity-beta-feature
=> Set topology key for pod anti-affinity

chart/voyager/templates/deployment.yaml, docs/user-guide/README.md, hack/deploy/with-rbac.yaml, hack/deploy/without-rbac.yaml
=> Disable critical addon feature

pkg/certificate/controller.go
Avoid getting provider secret if no `providerCredentialSecretName` provided
=> Avoid getting provider secret

third_party/forked/cloudprovider/providers/aws/aws.go
ref #372
From @greg-jaunt ,
> Kubernetes requires that only one SG with a KubernetesCluster tag can be assigned to one node/instance.  When I try to deploy another Kubernetes service I get:
`Error creating load balancer (will retry): Failed to create load balancer for service default/lease-external: Multiple tagged security groups found for instance i-0d3da7988c4d5aa98; ensure only the k8s security group is tagged`.  If I remove the KubernetesCluster tag from the Voyager-managed Ingress security group the error goes away.
=> Change ingress sg tag to VoyagerCluster from KubernetesCluster

api/annotations.go, pkg/haproxy/template.go, pkg/haproxy/template_test.go, pkg/haproxy/types.go, pkg/ingress/parser.go, test/e2e/ingress_tls_backend.go, test/framework/framework.go, test/framework/ingress_suite.go, test/framework/ingress_util.go, test/test-server/gen_cert.go, test/test-server/server.go, test/test-server/setup.sh
Setting `ingress.appscode.com/backend-tls` annotation in the service will set tls from haproxy to backend.
```
Available Options
ssl:
Creates a TLS/SSL socket when connecting to this server in order to cipher/decipher the traffic
if verify not set the following error may occurred
[/etc/haproxy/haproxy.cfg:49] verify is enabled by default but no CA file specified.
If you're running on a LAN where you're certain to trust the server's certificate,
please set an explicit 'verify none' statement on the 'server' line, or use
'ssl-server-verify none' in the global section to disable server-side verifications by default.
verify [none|required]:
Sets HAProxy‘s behavior regarding the certificated presented by the server:
none :
doesn’t verify the certificate of the server
required (default value) : …
```
=> TLS Backend

api/validator_test.go, pkg/haproxy/template.go, pkg/haproxy/template_test.go, pkg/haproxy/types.go, pkg/ingress/nodeport.go, pkg/ingress/parser.go, test/e2e/ingress_nodeport.go
ACLs sharing the same name
It is possible to use the same <aclname> for many ACLs, even if they don’t have the same matching criterion A logical OR applies between all of them
https://www.haproxy.com/doc/aloha/7.0/haproxy/acls.html#acls-sharing-the-same-name
=> Fix Host:Port Matching issue.

README.md, api/annotations.go, docs/README.md, docs/user-guide/ingress/README.md, docs/user-guide/ingress/basic-auth.md, glide.lock, glide.yaml, hack/docker/voyager/templates/default-frontend.cfg, hack/docker/voyager/templates/haproxy.cfg, hack/docker/voyager/templates/http-frontend.cfg, hack/docker/voyager/templates/stats.cfg, hack/docker/voyager/templates/userlist.cfg, hack/example/e2e.yaml, pkg/haproxy/template_test.go, pkg/haproxy/types.go, pkg/ingress/parser.go, test/e2e/e2e.go, test/e2e/ingress_basicauth.go, vendor/github.com/ovh/go-ovh/ovh/ovh.go, vendor/github.com/spf13/cobra/bash_completions.go, vendor/github.com/spf13/cobra/zsh_completions.go, vendor/github.com/tredoe/osutil/LICENSE-MPL.txt, vendor/github.com/tredoe/osutil/user/crypt/LICENSE, vendor/github.com/tredoe/osutil/user/crypt/common/base64.go, vendor/github.com/tredoe/osutil/user/crypt/common/doc.go, vendor/github.com/tredoe/osutil/user/crypt/common/salt.go, vendor/github.com/tredoe/osutil/user/crypt/crypt.go, vendor/github.com/tredoe/osutil/user/crypt/sha512_crypt/sha512_crypt.go, vendor/gopkg.in/ini.v1/ini.go, vendor/gopkg.in/ini.v1/struct.go
Basic Auth; Follows haproxy ingress controller standard https://github.com/kubernetes/ingress/tree/master/examples/auth/basic/haproxy HAProxy Ingress read user and password from auth file stored on secrets, one user and password per line.
Each line of the auth file should have: user and insecure password separated with a pair of colons: `<username>::<plain-text-passwd>`; or user and an encrypted password separated with colons: `<username>:<encrypted-passwd>` Secret name, realm and type are configured with annotations in the ingress
Auth can only be applied to HTTP backends.
```
// Only supported type is basic
AuthType = "ingress.kubernetes.io/auth-type"
// an optional string with authentication realm
AuthRealm = "ingress.kubernetes.io/auth-realm"
// name of the secret
AuthSecret = …
```
=> Implement Basic Auth for HTTP Ingresses

api/validator.go, third_party/forked/cloudprovider/cloud.go, third_party/forked/cloudprovider/providers/aws/aws.go, third_party/forked/cloudprovider/providers/azure/azure_util.go, third_party/forked/cloudprovider/providers/gce/gce.go
```
No node tags supplied and also failed to parse the given lists of hosts for tags. Abort creating firewall rule.
Stack trace:
/go/src/github.com/appscode/voyager/pkg/operator/ingress_tprs.go:100                      (*Operator).AddEngress
/go/src/github.com/appscode/voyager/pkg/operator/ingress_tprs.go:52                       (*Operator).initIngressTPRWatcher.func3
/go/src/github.com/appscode/voyager/vendor/k8s.io/client-go/tools/cache/controller.go:192 ResourceEventHandlerFuncs.OnAdd
<autogenerated>:54                                                                        (*ResourceEventHandlerFuncs).OnAdd
/go/src/github.com/appscode/voyager/vendor/k8s.io/client-go/tools/cache/controller.go:270 NewInformer.func1
/go/src/github.com/appscode/voyager/vendor/k8s.io/client-go/tools/cache/d …
```
=> Fix SG group name for GCE

apis/voyager/v1beta1/annotations.go, hack/docker/voyager/templates/http-backend.cfg, pkg/haproxy/template.go, pkg/haproxy/types.go, pkg/ingress/parser.go, test/e2e/ingress_ops.go
When affinity is set to cookie, the hash algorithm used: md5, sha, index.
=> Add support for `ingress.kubernetes.io/session-cookie-hash`.

hack/docker/voyager/templates/http-frontend.cfg
https://www.haproxy.com/blog/haproxy-and-http-strict-transport-security-hsts-header-in-http-redirects/
=> Fix HSTS header template

pkg/ingress/hostport.go, pkg/ingress/loadbalancer.go, pkg/ingress/nodeport.go, pkg/ingress/update.go, pkg/operator/ingress_crds.go
This is not needed anymore since HAProxy deployments watch all secrets in its namespace.
=> Remove UpdateRBAC mode.

hack/docker/voyager/templates/http-frontend.cfg, hack/docker/voyager/templates/tcp-frontend.cfg, pkg/haproxy/types.go, pkg/ingress/parser.go, pkg/tlsmounter/secret.go
=> Add support for CRL when using TLS Auth

apis/voyager/v1beta1/annotations.go, hack/docker/voyager/templates/default-backend.cfg, hack/docker/voyager/templates/http-backend.cfg, hack/docker/voyager/templates/tcp-backend.cfg, pkg/haproxy/template_test.go, pkg/haproxy/types.go, pkg/ingress/parser.go, test/e2e/ingress_ops.go, test/framework/ingress_util.go
Fixed #683 
Service annotations:
```
ingress.appscode.com/check: "true"
ingress.appscode.com/check-port: "5050"
```
Backend rules: 
https://github.com/appscode/voyager/blob/master/docs/user-guide/ingress/backend-rule.md
```
backendRule:
- 'option httpchk GET /testpath/ok'
- 'http-check expect rstring (testpath/ok)'
```
=> Enable server health check using service annotations and backend rules

apis/voyager/ingress.go, apis/voyager/v1beta1/ingress.go, apis/voyager/v1beta1/openapi_generated.go, apis/voyager/v1beta1/zz_generated.conversion.go, apis/voyager/v1beta1/zz_generated.deepcopy.go, apis/voyager/zz_generated.deepcopy.go, pkg/ingress/hostport.go, pkg/ingress/internal.go, pkg/ingress/loadbalancer.go, pkg/ingress/nodeport.go, pkg/ingress/update.go
=> Support ExternalIPs

apis/voyager/v1beta1/annotations.go, hack/docker/voyager/templates/default-backend.cfg, hack/docker/voyager/templates/http-backend.cfg, hack/docker/voyager/templates/tcp-backend.cfg, pkg/haproxy/types.go, pkg/ingress/parser.go, test/e2e/ingress_ops.go, test/e2e/ingress_tcp.go, test/framework/ingress_suite.go, test/framework/ingress_util.go
=> Add to backends the options for send-proxy variants for server.

apis/voyager/ingress.go, apis/voyager/v1beta1/ingress.go, apis/voyager/v1beta1/validator.go, apis/voyager/v1beta1/zz_generated.conversion.go, hack/docker/voyager/templates/http-frontend.cfg, hack/docker/voyager/templates/tcp-frontend.cfg, pkg/haproxy/types.go, pkg/ingress/parser.go, test/e2e/ingress_hostport.go, test/framework/ingress_util.go
Currently, Voyager will allow (or enforce, in the case of TCP rules) specifying a specific port to
expose services against, regardless of their internal service port. This commit extends this
functionality by allowing for specifying an optional bind address (IPv4 or IPv6), which defaults to
a wildcard ('*'), which binds to all available addresses.
An example 'Ingress' definition might look like:
```
apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
name: ingress
namespace: default
labels:
app: voyager
annotations:
ingress.appscode.com/type: HostPort
spec:
rules:
- host: deuill.org
http:
address: 203.0.113.101
paths:
- backend:
serviceName: deuill.web
servicePort: 80
- host: mail.deuill.org
tcp:
address: 203.0.113.102
port: 25
backend:
serviceName: postfix.mail
servicePort: …
```
=> Allow for binding HTTP or TCP ingress rules to specific addresses

hack/docker/voyager/templates/default-frontend.cfg, hack/docker/voyager/templates/http-frontend.cfg
set-header removes first any existing header field matching <name>.
This avoid adding duplicate header.
=> Use http-response set-header instead of rspadd

apis/voyager/v1beta1/annotations.go, pkg/ingress/parser.go
=> Support rewrite-target annotation

hack/docker/voyager/templates/http-backend.cfg, hack/docker/voyager/templates/http-frontend.cfg, pkg/haproxy/template.go
ref:
https://www.haproxy.com/documentation/aloha/7-0/haproxy/acls/
Backend names are empty for paths that are auto injected for redirect rules. So, we can't assume that backend names will always be present.
=> Don't use backend name to generate acl name

docs/README.md, docs/developer-guide/README.md, docs/user-guide/certificate/README.md, docs/user-guide/ingress/README.md
Need this aliases otherwise following links will not work mentioned in /docs/README.md
- https://github.com/appscode/voyager/blob/master/docs/developer-guide/README.md
- https://github.com/appscode/voyager/blob/master/docs/CONTRIBUTING.md
=> Add aliases for README file

glide.lock, glide.yaml, vendor/github.com/dnsimple/dnsimple-go/dnsimple/accounts.go, vendor/github.com/dnsimple/dnsimple-go/dnsimple/domains_email_forwards.go, vendor/github.com/kelseyhightower/passwd/LICENSE, vendor/github.com/kelseyhightower/passwd/user/lookup.go, vendor/github.com/kelseyhightower/passwd/user/lookup_passwd.go, vendor/github.com/kelseyhightower/passwd/user/user.go, vendor/github.com/spf13/cobra/doc/md_docs.go, vendor/golang.org/x/oauth2/LICENSE, vendor/golang.org/x/oauth2/google/default.go, vendor/golang.org/x/oauth2/google/sdk.go, vendor/golang.org/x/oauth2/internal/doc.go, vendor/golang.org/x/oauth2/internal/oauth2.go, vendor/golang.org/x/oauth2/internal/token.go, vendor/golang.org/x/oauth2/internal/transport.go, vendor/golang.org/x/oauth2/oauth2.go, vendor/golang.org/x/oauth2/token.go
Our forked version does not call os/user.Current() method and as such does not require cgo to build.
=> Use forked golang/x/oauth2 library

pkg/certificate/controller.go
=> Fix panic when crt.status.LastIssuedCertificate is missing on renew

pkg/haproxy/renderer_test.go, pkg/haproxy/template_test.go, pkg/operator/operator_test.go
Updating the tests according to the current implementation.
=> Fix unit tests

glide.lock, vendor/github.com/appscode/kube-mon/agents/agents.go, vendor/github.com/appscode/kube-mon/agents/coreosprometheusoperator/lib.go, vendor/github.com/appscode/kube-mon/api/types.go, vendor/github.com/appscode/kube-mon/parser.go
This PR updates kube-mon. It fixes the scenario where we don't set service-monitor-endpoint-port annotation and it should fallback to default exporter port. 
What happens currently is that if service-monitor-endpoint-port annotation is not defined it will successfully create the ServiceMonitor and the the *-stats service but it does not add the port named 'http' to the service definition so the endpoints available won't match the job definition in prometheus and it does not add the sidecar container to the deployment spec either.
=> Updating kube-mon so service-monitor-endpoint-port is optional

hack/docker/voyager/templates/http-frontend.cfg
ref: https://www.haproxy.com/documentation/aloha/7-0/traffic-management/lb-layer7/http-redirection/
Fixes #816
=> Preserve original HTTP verb on redirect

apis/voyager/v1beta1/annotations.go, docs/concepts/ingress-types/nodeport.md, hack/docker/voyager/templates/http-frontend.cfg, pkg/haproxy/api/types.go, pkg/haproxy/template/template.go, pkg/ingress/parser.go, test/e2e/ingress_nodeport.go
```yaml
apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
name: test-ingress
namespace: default
annotations:
ingress.appscode.com/type: NodePort
spec:
rules:
- host: voyager.appscode.test
http:
port: '8989'
nodePort: '32666'
paths:
- path: /foo
backend:
serviceName: test-server
servicePort: '80'
```
Generated haproxy.cfg:
```
global
daemon
stats socket /tmp/haproxy
server-state-file global
server-state-base /var/state/haproxy/
log /dev/log local0 info
log /dev/log local0 notice
tune.ssl.default-dh-param 2048
ssl-default-bind-ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128 …
```
=> Use service port by default for LB type nodeport

pkg/operator/operator.go
Because it is a blocking call.
=> Run service monitor informer in its own go routine.

test/e2e/e2e.go, test/e2e/options.go, vendor/github.com/appscode/kutil/apiextensions/v1beta1/kubernetes.go, vendor/github.com/appscode/kutil/core/v1/pod.go, vendor/github.com/appscode/kutil/core/v1/service.go, vendor/github.com/appscode/kutil/tools/analytics/analytics.go
=> Fix errors while updating existing CRD 

apis/voyager/v1beta1/validator.go, docs/setup/install.md
i've applied a newly built haproxy image to the crash looping deployment and changed the args to `-cloudprovider=metallb` and the pod started up successfully.
running curl against the assigned LB-IP produced a 503 and a proper log in the container
`local0.info: Apr  5 12:18:35 haproxy[30]: 10.40.0.0:63780 [05/Apr/2018:12:18:35.428] http-0_0_0_0-80 http-0_0_0_0-80/&lt;NOSRV&gt; -1/-1/-1/-1/1 503 212 - - SC-- 0/0/0/0/0 0/0 "GET / HTTP/1.1"`
=> #970 Added metallb as a cloud provider option

hack/docker/voyager/templates/http-frontend.cfg, pkg/haproxy/api/types.go, pkg/haproxy/template/template.go, pkg/ingress/nodeport.go, pkg/ingress/parser.go
fixes #967 
https://serverfault.com/questions/831065/i-need-to-configure-haproxy-with-multiple-ssl-ports
=> Fix SSL redirect for LB type NodePort

apis/voyager/v1beta1/diff.go, apis/voyager/v1beta1/validator.go, apis/voyager/v1beta1/validator_test.go, pkg/ingress/parser.go
- GetHost() is moved to API and used in validator to check path conflicts
- In parser.go, GetHost() is done only when extracting data from rule.Host, in other cases we don't need it, since they are populated from rule.Host
- If TLS is defined for `*` host and we try to merge empty-host with `*` host, it will cause conflicting TLS error, is it OK ?
=> Updated validator for merging empty-host with wildcard-host  

test/framework/ingress_util.go
- For LoadBalancer / NoderPort `url = <minikube-ip>:<service-node-port>`
- For HostPort (headless service) `url = <minikube-ip>:<service-port>`
=> Fixed minikube urls for LB type hostport

pkg/operator/operator.go
This happens when operator pod restarts. The webhook server is not ready yet.
=> Don't exit if migration fails.

pkg/ingress/loadbalancer.go
This fixes #1105 by adding metallb to the list of cloud providers that support having the LoadBalancerIP set.
=> Add metallb to providers that can have LoadBalancerIP set.

docs/guides/ingress/dns/external-dns.md
I'm using HostPort type ingress.
For me annotation on service works, not on pod.
Using external-dns version 0.5.2
=> Fix documentation about external-dns service

docs/examples/monitoring/coreos-operator/demo-0.yaml, docs/examples/monitoring/coreos-operator/rbac/demo-0.yaml, docs/guides/ingress/monitoring/using-coreos-prometheus-operator.md
If you follow docs step by step, namespace gets created manually in the beginning.
Moreover it will be easier to `kubectl delete -f https://raw.githubusercontent.com/appscode/voyager/7.0.0/docs/examples/monitoring/coreos-operator/...` later without complete namespace removal
=> Do not create namespace from yaml, it gets created with kubectl manually

hack/deploy/operator.yaml
In a mixed cluster comprised of both Windows and Linux containers, this nodeSelector is required to ensure voyager is deployed to the linux container.
=> Add nodeSelector for the operator

api/openapi-spec/swagger.json, apis/voyager/v1beta1/crds.yaml, apis/voyager/v1beta1/ingress.go, apis/voyager/v1beta1/openapi_generated.go
In the latest version of kubernetes server having description at the
root of the schema is invalid and blocks creation of the schema.
The operator logs show the following error:
```
I0630 01:45:19.699218       1 logs.go:19] CustomResourceDefinition.apiextensions.k8s.io "ingresses.voyager.appscode.com" is invalid: spec.validation.openAPIV3Schema: Invalid value: apiextensions.JSONSchemaProps{ID:"", Schema:"", Ref:(*string)(nil), Description:"Custom Ingress type for Voyager.", Type:"", Format:"", Title:"", Default:(*apiextensions.JSON)(nil), Maximum:(*float64)(nil), ExclusiveMaximum:false, Minimum:(*float64)(nil), ExclusiveMinimum:false, MaxLength:(*int64)(nil), MinLength:(*int64)(nil), Pattern:"", MaxItems:(*int64)(nil), MinItems:(*int64)(nil), UniqueItems:false, MultipleOf:(*float64)(nil), …
```
=> Remove description on root schema

pkg/ingress/hostport.go, pkg/ingress/internal.go, pkg/ingress/loadbalancer.go, pkg/ingress/nodeport.go
Fixes #1251
Sort pod annotations to make `ingress.appscode.com/last-applied-annotation-keys` stable and avoid triggering rolling update
=> Sort pod annotations to avoid template changes

chart/voyager/templates/deployment.yaml, chart/voyager/values.yaml
This translates the `--template-cfgmap` switch of the install script
to the helm chart.
=> add support for custom templates from config map to chart

api/crds/ingress.yaml, api/openapi-spec/swagger.json, apis/voyager/v1beta1/ingress.go, apis/voyager/v1beta1/openapi_generated.go, apis/voyager/v1beta1/zz_generated.deepcopy.go, pkg/ingress/hostport.go, pkg/ingress/internal.go, pkg/ingress/loadbalancer.go, pkg/ingress/nodeport.go
Allow users to specify probes for generated deployments
(also, terminationGracePeriodSeconds). 
Tested using HAProxy's builtin `monitor-uri`.
Fixes #1262
=> Support readinessProbe and livenessProbe

docs/guides/ingress/tcp/overview.md
Using SNI, Voyager supports multiple TCP rules listening to same port for different hosts.
=> Update TCP docs

docs/guides/ingress/tls/overview.md
Should be certificates.voyager.appscode.com, I think.
```bash
kubectl get crd -l app=voyager
NAME                                CREATED AT
certificates.voyager.appscode.com   2019-01-15T20:24:31Z
ingresses.voyager.appscode.com      2019-01-15T20:24:31Z
```
=> readme: overview: certificates.voyager.appscode.com

docs/guides/ingress/http/single-service.md
It should be more clear to understand which service is the default one and when its ingress is hit.
=> readme: single-service update

docs/guides/ingress/http/single-service.md
The Ingress "ingress-test" is invalid: spec.backend.servicePort: Invalid value: "80": must contain at least one letter or number (a-z, 0-9)
=> remove single quotes from servicePort

chart/voyager/templates/cluster-role.yaml, hack/deploy/rbac-list.yaml, pkg/ingress/controller.go, pkg/ingress/hostport.go, pkg/ingress/internal.go, pkg/ingress/loadbalancer.go, pkg/ingress/nodeport.go
- Change in `ingress.appscode.com/replicas` will only take effect when there's no hpa controlling that ingress deployment
=> Allow replica change when no hpa

apis/voyager/v1beta1/annotations.go, docs/examples/ingress/types/hostport/haproxy.cfg, docs/examples/ingress/types/internal/haproxy.cfg, docs/examples/ingress/types/loadbalancer/haproxy.cfg, docs/examples/ingress/types/nodeport/haproxy.cfg, docs/guides/ingress/configuration/accept-proxy.md, docs/guides/ingress/configuration/annotations.md, docs/guides/ingress/configuration/body-size.md, docs/guides/ingress/configuration/config-volumes.md, docs/guides/ingress/configuration/default-options.md, docs/guides/ingress/configuration/default-timeouts.md, docs/guides/ingress/configuration/http-2.md, docs/guides/ingress/configuration/loadbalance-algorithm.md, docs/guides/ingress/configuration/max-connections.md, docs/guides/ingress/configuration/node-port.md, docs/guides/ingress/configuration/rate-limit.md, docs/guides/ingress/configuration/rewrite-target.md, docs/guides/ingress/configuration/ssl-passthrough.md, docs/guides/ingress/configuration/ssl-redirect.md, docs/guides/ingress/configuration/whitelist.md, docs/guides/ingress/http/hsts.md, docs/guides/ingress/tcp/tcp-sni.md, hack/example/haproxy_generated.cfg
Default timeout values in haproxy configuration is now:
```
timeout  connect         5s
timeout  client          50s
timeout  client-fin      50s
timeout  server          50s
timeout  tunnel          50s
```
=> Change timeout connect to 5s

hack/deploy/voyager.sh
Allow to select an ingress class on installation script. Useful to follow instructions on the [FAQ](https://appscode.com/products/voyager/7.1.1/concepts/overview/#faq) *How do I run Voyager with other Ingress controllers in the same cluster?*
=> Add --ingress-class to hack/deploy/voyager.sh

chart/voyager/templates/cluster-role.yaml
#1397 removed the `--rbac` flag from templates but for `cluster-role.yaml` `{{ end }}` was left in the template by mistake. This throws errors like mentioned in #1433 
This PR just removed the extraneous `{{ end }}`
=> Fix broken helm chart: unexpected end definition in cluster-role.yaml

charts/voyager/templates/deployment.yaml
Fix YAML parse error converting YAML to JSON on line 82.
> `Error: YAML parse error on voyager/templates/deployment.yaml: error converting YAML to JSON: yaml: line 82: mapping values are not allowed in this contex`
=> Fix helm v3.0.0 chart error on install

go.mod, vendor/modules.txt
The commit we're interested in is
googleapis/google-cloud-go@fbf2f51 ,
which disables an aggressive 2-second timeout for awaiting headers from
the compute metadata service.
When workload identity is enabled on a cluster, a different endpoint is
used under the hood for compute metadata, and this endpoint can often
take more than 2 seconds to return headers.
=> Bump cloud.google.com/go to get timeout fix

charts/voyager/templates/cluster-role.yaml
The Voyager Operator ClusterRole template of the Helm chart misses the`ingresses/status` resource of the apiGroup `extensions`.
The PR should fix #1483.
=> Add missing ingresses/status resource to operator ClusterRole

charts/voyager/templates/deployment.yaml, docs/reference/voyager_run.md, pkg/cmds/server/options.go
These options actually appear in the chart, and allowing them to set means
users can use their own naming convention when it comes to repositories.
The chart change may not actually be backwards compatible. If users have this
option set currently, it will have no effect, and so if it's set to something
other than the default (haproxy and voyager respectively), then the functionality
will change.
Fixes #1449
This is my first contribution, so let me know if the PR can be adjusted in any way.
=> Haproxy exporter image repository

pkg/operator/certificate_crds.go
The `CheckCertificates()` goroutine should run an infinite loop, but it can exit via `return` after certain errors.
Because nothing restarts the goroutine, certificates simply stop getting checked for expiry when errors happen! This explains why renewals sporadically stopped in #1303 and #1443. No way to restart the loop either, other than restarting the pod.
This problem is hard to trace because even though the causing error is recorded as a Kubernetes event, it gets logged at most once (because the loop exits right after) and events are removed after one hour by default.
I changed the relevant `return` statements into `continue`. This not only ensures the loop is infinite so certificate renewals are always retried later despite errors, but also continually logs errors that are not …
=> Never exit certificates renewal infinite loop

apis/voyager/v1beta1/annotations.go, pkg/ingress/controller.go, pkg/operator/config.go, pkg/operator/operator.go, pkg/operator/statefulset.go
Now annotation `ingress.appscode.com/workload-kind` only support Deployment and DeamonSet, but sometimes need workload type is StatefulSet.
ingress use annotation`ingress.appscode.com/workload-kind: StatefulSet`, so the workload will be StatefulSet.
=> workload-kind support StatefulSet

pkg/cmds/server/options.go
In the previous change this incorrectly used the ImageTag when it
should've been the ImageRepository option
Fixes https://github.com/voyagermesh/voyager/issues/1501
=> Correctly load (HAProxy|Exporter)ImageRepository options

README.md
This was presumably broken when the website/repository was moved.
Fixes #1506
=> Fix README.md documentation links

pkg/haproxy/controller/controller.go, pkg/haproxy/controller/reload.go
This PR fixes #1334. 
As _elynnyap_ explained, the "503  errors" bug is actually caused by several haproxy processes running in parallel. 
This can happen when several `haproxy` commands are executed at the same time. 
In `controller.go` (`Run`), there is a 30 seconds ticker that checks if the haproxy daemon exists, and if it doesn't, it starts a new one, otherwise it does nothing. 
To determine whether the process exists or not, it reads `/var/run/haproxy.pid`, and then tries to find a process with that pid. 
But in `reload.go`, there is another function `startOrReloadHaproxy` that is called whenever there is a config/cert change. It does the same daemon existence check, and then either starts a new haproxy, or reloads the existing one. 
The bug occurs when both execute at the same time. …
=> Avoid concurrent haproxy starts or reloads

pkg/operator/certificate_crds.go
The `CheckCertificates` goroutine should run an infinite loop, running one iteration every 5 minutes, to ensure certificates are correctly generated and never expire. 
Release v1.12.0 introduced a bug (#1522) which was making this goroutine run only once (after 5 minutes), and then block forever. Indeed, a `for range` loop receives values from the channel repeatedly until it is closed. And `Time.After` waits for 5 minutes and then sends the current time on the returned channel, but then neither sends any other value nor closes the channel, so it just blocks forever. 
Instead, just use an infinite loop that waits for `Time.After` to send its value, then end the iteration and let a new one start (more or less like it was in v1.11.1 and before).
=> fix CheckCertificates goroutine to run an infinite loop again

pkg/operator/certificate_crds.go
This PR fixes another bug with certificates creation, that has been in Voyager for a long time. 
When you create a new certificate (or update an existing one, or restart `voyager-operator`), the `reconcileCertificate` function will be called instantly, trying to issue that certificate (if needed). In my case (DNS challenge), it takes approximately one minute to obtain the certificate (need to add the TXT record, check propagation, wait for LE to issue it...)
Meanwhile, there is a goroutine looping (one iteration every 5 minutes): `CheckCertificates`. That goroutine will often try to issue the same certificate at the same time. And that can cause a lot of different bugs with different providers. 
For example, with `gcloud`, I always get the `alreadyExists` error, because the TXT record …
=> Avoid issuing cert two times at creation

docs/CHANGELOG-v2022.01.01.md
Release: v2022.01.01
Release-tracker: https://github.com/voyagermesh/CHANGELOG/pull/11
=> Prepare for release v2022.01.01

docs/CHANGELOG-v2022.01.07.md
Release: v2022.01.07
Release-tracker: https://github.com/voyagermesh/CHANGELOG/pull/12
=> Prepare for release v2022.01.07

docs/CHANGELOG-v2022.01.10.md
Release: v2022.01.10
Release-tracker: https://github.com/voyagermesh/CHANGELOG/pull/13
=> Prepare for release v2022.01.10

docs/CHANGELOG-v2022.03.17.md
Release: v2022.03.17
Release-tracker: https://github.com/voyagermesh/CHANGELOG/pull/17
=> Prepare for release v2022.03.17

docs/CHANGELOG-v2022.04.13.md
Release: v2022.04.13
Release-tracker: https://github.com/voyagermesh/CHANGELOG/pull/18
=> Prepare for release v2022.04.13

docs/CHANGELOG-v2022.06.20.md
Release: v2022.06.20
Release-tracker: https://github.com/voyagermesh/CHANGELOG/pull/19
=> Prepare for release v2022.06.20

docs/CHANGELOG-v2022.12.11.md
Release: v2022.12.11
Release-tracker: https://github.com/voyagermesh/CHANGELOG/pull/23
=> Prepare for release v2022.12.11

docs/CHANGELOG-v2023.02.22.md
Release: v2023.02.22
Release-tracker: https://github.com/voyagermesh/CHANGELOG/pull/24
=> Prepare for release v2023.02.22

docs/CHANGELOG-v2023.05.16.md
Release: v2023.05.16
Release-tracker: https://github.com/voyagermesh/CHANGELOG/pull/27
=> Prepare for release v2023.05.16

docs/CHANGELOG-v2023.9.18.md
Release: v2023.9.18
Release-tracker: https://github.com/voyagermesh/CHANGELOG/pull/28
=> Prepare for release v2023.9.18

docs/CHANGELOG-v2024.3.18.md
Release: v2024.3.18
Release-tracker: https://github.com/voyagermesh/CHANGELOG/pull/29
=> Prepare for release v2024.3.18

docs/CHANGELOG-v2024.8.30.md
Release: v2024.8.30
Release-tracker: https://github.com/voyagermesh/CHANGELOG/pull/32
=> Prepare for release v2024.8.30

docs/CHANGELOG-v2025.5.30.md
Release: v2025.5.30
Release-tracker: https://github.com/voyagermesh/CHANGELOG/pull/36
=> Prepare for release v2025.5.30

docs/CHANGELOG-v2025.9.19.md
Release: v2025.9.19
Release-tracker: https://github.com/voyagermesh/CHANGELOG/pull/38
=> Prepare for release v2025.9.19
